module.exports = [
  {
    "nome": "Óleo de Forma Etérea",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Aplicar no corpo (10 min) concede o efeito da magia Forma Etérea por 1 hora.",
    "descricao": "Untar este óleo no corpo e roupas (requer 10 minutos de aplicação) concede o efeito da magia *Forma Etérea* por 1 hora."
  },
  {
    "nome": "Óleo de Precisão",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Aplicar em uma arma ou 5 munições concede bônus de +3 em jogadas de ataque e dano por 1 hora.",
    "descricao": "Untar uma arma ou até 5 munições com este óleo translúcido (requer 1 minuto) concede a elas um bônus de +3 em jogadas de ataque e dano por 1 hora."
  },
  {
    "nome": "Óleo Escorregadio",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede os benefícios de Movimentação Livre por 8 horas, ou derramado no chão cria área escorregadia idêntica a Área Escorregadia por 8 horas.",
    "descricao": "Aplicar no corpo concede os benefícios da magia *Movimentação Livre* por 8 horas. Despejar no chão cobre um quadrado de 3 metros como na magia *Área Escorregadia* por 8 horas."
  },
  {
    "nome": "Olho de Megera",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Gema através da qual um conciliábulo de megas pode enxergar e ouvir como se estivessem presentes.",
    "descricao": "Criado por um conciliábulo de megas. As megas podem ver e ouvir através dele como se estivessem presentes no local. Destruir o olho causa 3d10 dano Psíquico e cega as megas do conciliábulo por 24 horas."
  },
  {
    "nome": "Olho e Mão de Vecna",
    "tipo": "Item Maravilhoso",
    "subtipo": "Artefato",
    "tipo_linha": "Item Maravilhoso, Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização e Enxerto Cirúrgico",
    "resumo": "Supremos artefatos necromânticos de Vecna: Raio-X, Visão Verdadeira, Força 20, +2d8 dano gélido desarmado, vasta lista de magias sombrias de 8 cargas e risco de posse demoníaca.",
    "descricao": "Devem ser enxertados no lugar do próprio olho ou mão.\n- **Olho:** Visão de Raio-X, Visão Verdadeira 36 m, e conjura *Clarividência*, *Coroa da Loucura*, *Desintegração*, *Raio Polar* e *Visão da Verdade*.\n- **Mão:** Força fixada em 20, ataques desarmados causam +2d8 dano Gélido, e conjura *Dedo da Morte*, *Mãos Flamejantes*, *Queda Suave*, *Sono* e *Vagar*.\n- **Ambos:** Imunidade a Veneno/Doença, crítico cura PV e conjura *Desejo* 1x a cada 30 dias."
  },
  {
    "nome": "Olho Ersatz",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Substitui um olho biológico perdido, enxergando perfeitamente através dele.",
    "descricao": "Este olho artificial de vidro ou pedra substitui um olho perdido. Enquanto estiver inserido na órbita ocular, funciona exatamente como um olho normal e não pode ser removido contra a sua vontade."
  },
  {
    "nome": "Olhos Ampliadores da Visão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Lentes de cristal que concedem Vantagem em testes de Investigação para examinar objetos a até 30 cm e ler textos minúsculos.",
    "descricao": "Estas lentes de cristal se ajustam aos seus olhos. Concedem Vantagem em testes de Inteligência (Investigação) para examinar detalhes minúsculos a até 30 cm de distância."
  },
  {
    "nome": "Olhos da Águia",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede Vantagem em testes de Percepção baseados em visão e permite enxergar detalhes nítidos a até 1,5 km de distância.",
    "descricao": "Estas lentes de cristal cristalino concedem Vantagem em testes de Sabedoria (Percepção) que dependam da visão. Em condições normais, você enxerga detalhes nítidos a até 1,5 quilômetro."
  },
  {
    "nome": "Olhos de Enfeitiçar",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para conjurar Enfeitiçar Pessoa (CD 13) ao fixar o olhar em um alvo.",
    "descricao": "Estes óculos têm 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga para conjurar *Enfeitiçar Pessoa* (CD 13) ao olhar diretamente nos olhos do alvo."
  },
  {
    "nome": "Olhos Noturnos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Visão no Escuro de 18 metros (ou amplia em +18 m se já possuir).",
    "descricao": "Enquanto estiver usando estas lentes escuras, você tem Visão no Escuro com alcance de 18 metros. Se você já tiver Visão no Escuro, o alcance aumenta em 18 metros adicionais."
  },
  {
    "nome": "Onda",
    "tipo": "Arma",
    "subtipo": "Tridente",
    "tipo_linha": "Arma (Tridente), Lendário (Requer Sintonização por um Devoto dos Mares)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Devoto dos Mares",
    "resumo": "Tridente senciente +3 (+1d8 radiante ou necrótico); no crítico, drena metade dos PV máximos da criatura (dano Necrótico); confere respirar na água, natação 18 m e magias aquáticas.",
    "descricao": "Tridente senciente +3 em ataque/dano. Ao obter um Acerto Crítico contra uma criatura, o alvo sofre dano Necrótico adicional igual à metade dos seus Pontos de Vida máximos. Concede respiração subaquática, Deslocamento de Natação de 18 m, telepatia aquática e conjura *Criar ou Destruir Água*, *Controlar Água* e *Dominar Monstro* (apenas aquáticos)."
  },
  {
    "nome": "Opressor",
    "tipo": "Arma",
    "subtipo": "Espada Grande",
    "tipo_linha": "Arma (Espada Grande), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Espada Grande +3 que causa dano em área cortando até 3 alvos adjacentes e drena forças dos alvos atingidos.",
    "descricao": "Concede +3 em ataque e dano. Ao realizar a ação de Ataque, o corte atinge simultaneamente até três alvos dentro do alcance, forçando salvaguardas de Constituição para não sofrerem redução no deslocamento."
  },
  {
    "nome": "Orbe Flutuante",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Orbe de cristal que flutua a até 1,5 m de altura por comando verbal, iluminando suavemente.",
    "descricao": "Ao soltar este orbe de cristal com a palavra de comando, ele paira imóvel a até 1,5 m do chão e emite Meia-luz em raio de 4,5 metros."
  },
  {
    "nome": "Orbes Dracônicos",
    "tipo": "Item Maravilhoso",
    "subtipo": "Artefato",
    "tipo_linha": "Item Maravilhoso, Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Orbe senciente lendário que abriga a alma de um dragão ancestral: telepatia, detecção de dragões em 60 km, chamada dracônica irresistível e magias de 7 cargas.",
    "descricao": "Criados para dominar dragões. Permite chamar todos os dragões malignos em 60 km. Concede Visão no Escuro 36 m, imunidade a sopros dracônicos e conjura *Vidência*, *Detectar Pensamentos*, *Sugestão* e *Paralisar Monstro* (CD 18)."
  },
  {
    "nome": "Pedra da Boa Sorte (Pedra-da-Sorte)",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede um bônus de +1 em todos os testes de atributo e salvaguardas enquanto carregada.",
    "descricao": "Enquanto esta ágata polida estiver com você, você ganha um bônus de +1 em testes de atributo e em todas as salvaguardas."
  },
  {
    "nome": "Pedra de Controlar Elementais da Terra",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite invocar um Elemental da Terra obediente por até 1 hora 1x ao dia ao colocá-la na terra ou pedra.",
    "descricao": "Ao colocar esta pedra no chão ou na rocha por 1 minuto, invoca um **Elemental da Terra** leal por 1 hora (1x ao dia)."
  },
  {
    "nome": "Pedra de Ioun",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raridade Variável (Requer Sintonização)",
    "raridade": "Raridade Variável",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Pedras mágicas lapidadas que orbitam a cabeça concedendo bônus contínuos (+2 em atributos, absorção de magias, +1 CA, mestria, etc.).",
    "descricao": "Flutuam em órbita ao redor da cabeça do usuário:\n- **Absorção (Muito Raro):** Absorve até 20 círculos de magias.\n- **Agilidade (Muito Raro):** +2 em Destreza (máx 20).\n- **Compreensão (Muito Raro):** +2 em Sabedoria (máx 20).\n- **Fortaleza (Muito Raro):** +2 em Constituição (máx 20).\n- **Força (Muito Raro):** +2 em Força (máx 20).\n- **Intelecto (Muito Raro):** +2 em Inteligência (máx 20).\n- **Liderança (Muito Raro):** +2 em Carisma (máx 20).\n- **Mestria (Lendário):** Bônus de Proficiência aumenta em +1.\n- **Proteção (Raro):** +1 na Classe de Armadura.\n- **Regeneração (Lendário):** Recupera 15 PV por hora.\n- **Reserva (Raro):** Armazena até 3 círculos de magias.\n- **Sustento (Raro):** Não precisa comer ou beber."
  },
  {
    "nome": "Pedras Mensageiras",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Par de pedras emparelhadas que permitem conjurar a magia Mensagem ou Enviar através de qualquer distância (até outros planos).",
    "descricao": "Vêm em par. Segurar uma pedra como ação Usar Magia permite conjurar a magia *Enviar* diretamente para o portador da outra pedra, em qualquer distância e mesmo em planos diferentes (1x ao dia)."
  },
  {
    "nome": "Perfume de Encantamento",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Frasco de perfume com 1d3+1 doses; aplicar concede Vantagem em testes de Carisma contra Humanoides por 1 hora.",
    "descricao": "Frasco com 1d3+1 doses. Aplicar na pele concede Vantagem em todos os testes de Carisma realizados contra Humanoides por 1 hora."
  },
  {
    "nome": "Pergaminho da Invocação de Titã",
    "tipo": "Pergaminho",
    "subtipo": "",
    "tipo_linha": "Pergaminho, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pergaminho lendário que invoca um Titã ou Tarrasque destruidor por 1 hora antes de ser consumido.",
    "descricao": "Ler este pergaminho consome-o para conjurar e invocar uma monstruosidade colossal titanica sob seu controle parcial por 1 hora."
  },
  {
    "nome": "Pergaminho de Círculo da Proteção",
    "tipo": "Pergaminho",
    "subtipo": "",
    "tipo_linha": "Pergaminho, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Cria um cilindro protetor de 3 m de raio por 5 minutos repelindo um tipo de criatura (Aberração, Celestial, Elemental, Fada, Ínfero ou Morto-Vivo).",
    "descricao": "Ao ler este pergaminho (ação Usar Magia), cria uma barreira de 3 metros de raio que impede a entrada e ataques de um tipo específico de criatura por 5 minutos."
  },
  {
    "nome": "Pergaminho Mágico",
    "tipo": "Pergaminho",
    "subtipo": "",
    "tipo_linha": "Pergaminho, Raridade Variável",
    "raridade": "Raridade Variável",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Contém uma magia gravada em pergaminho; pode ser conjurada sem componentes materiais e desintegra-se após o uso.",
    "descricao": "Contém uma magia específica gravada. Se a magia estiver na lista da sua classe, você pode conjurá-la lendo o pergaminho sem componentes materiais. O pergaminho é consumido em cinzas após a leitura.\n\n| Círculo | Raridade | CD | Ataque |\n| :--- | :--- | :--- | :--- |\n| Truque | Comum | 13 | +5 |\n| 1º | Comum | 13 | +5 |\n| 2º | Incomum | 13 | +5 |\n| 3º | Incomum | 15 | +7 |\n| 4º | Raro | 15 | +7 |\n| 5º | Raro | 17 | +9 |\n| 6º | Muito Raro | 17 | +9 |\n| 7º | Muito Raro | 18 | +10 |\n| 8º | Muito Raro | 18 | +10 |\n| 9º | Lendário | 19 | +11 |"
  },
  {
    "nome": "Periapto de Cicatrização",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Estabiliza o usuário automaticamente no início do turno ao estar morrendo com 0 Pontos de Vida.",
    "descricao": "Enquanto estiver usando este amuleto com pedras preciosas, se você começar seu turno com 0 Pontos de Vida, você é automaticamente estabilizado."
  },
  {
    "nome": "Periapto de Proteção Contra Veneno",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Neutraliza qualquer veneno no seu organismo instantaneamente ao ser colocado ou sofrer envenenamento.",
    "descricao": "Enquanto estiver usando este pingente, qualquer veneno inoculado ou ingerido em seu organismo é imediatamente neutralizado e você tem Imunidade à condição Envenenado."
  },
  {
    "nome": "Periapto de Saúde",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Imunidade total a todas as doenças não mágicas e mágicas.",
    "descricao": "Você é imune a contrair qualquer tipo de doença enquanto estiver usando este amuleto."
  },
  {
    "nome": "Pérola de Poder",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização por um Conjurador)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Ação Usar Magia para recuperar um espaço de magia gasto de até 3º círculo 1x ao dia.",
    "descricao": "Enquanto estiver segurando esta pérola, você pode executar uma ação Usar Magia para recuperar um espaço de magia de até 3º círculo gasto (1x ao dia)."
  },
  {
    "nome": "Pigmentos Maravilhosos de Nolzur",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Potes de tinta que tornam reais objetos inanimados pintados em superfícies (portas, pontes, ouro, comida, poços).",
    "descricao": "Permite pintar em qualquer superfície. Tudo que for pintado (até 90 m² de área e profundidade) torna-se matéria real inanimada e permanente após 10 minutos de pintura."
  },
  {
    "nome": "Pó da Seca",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Absorve instantaneamente até 380.000 litros de água transformando-se em uma bolinha de gude de retenção.",
    "descricao": "Jogado em um corpo de água, absorve instantaneamente até 380 mil litros de água em cubo de 4,5 m, condensando tudo em uma pequena pérola de gude que pode ser quebrada depois para liberar a água."
  },
  {
    "nome": "Pó de Desaparecimento",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Lançado no ar, concede a condição Invisível a você e criaturas em 3 m por 2d4 minutos (atacar encerra).",
    "descricao": "Lançado ao ar como ação Usar Objeto, torna você e criaturas a até 3 metros Invisíveis por 2d4 minutos. A invisibilidade se encerra para uma criatura que atacar ou conjurar magia."
  },
  {
    "nome": "Pó de Espirro-engasgo",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Parece pó de desaparecimento, mas causa tosse incontrolável (Incapacitado e sufocando com CD 15 Con) em raio de 6 metros.",
    "descricao": "Lançado no ar em 6 m de raio: qualquer criatura que precise respirar deve ser bem-sucedida em salvaguarda de Constituição CD 15 ou fica Incapacitada e sufocando por 1d4 rodadas."
  },
  {
    "nome": "Poção Bafo de Fogo",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite exalar fogo como Ação Bônus até 3 vezes em 1 hora, causando 4d6 de dano Ígneo a até 9 m (CD 13 Des).",
    "descricao": "Após beber, você pode executar uma Ação Bônus para exalar fogo em um alvo a até 9 metros. O alvo realiza uma salvaguarda de Destreza CD 13, sofrendo 4d6 pontos de dano Ígneo se falhar ou metade se passar. Permite até 3 exalações dentro de 1 hora."
  },
  {
    "nome": "Poção da Saúde",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Cura todas as doenças, neutraliza venenos e encerra as condições Cego, Surdo e Envenenado.",
    "descricao": "Beber esta poção cura todas as doenças que afetam você, neutraliza venenos em seu organismo e encerra as condições Cego, Surdo e Envenenado."
  },
  {
    "nome": "Poção das Formas Gasosas",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede o efeito da magia Forma Gasosa por 1 hora (sem requerer Concentração).",
    "descricao": "Ao beber esta poção esfumaçada, você adquire o efeito da magia *Forma Gasosa* por 1 hora sem requerer Concentração."
  },
  {
    "nome": "Poção de Amizade Animal",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite conjurar Amizade Animal (CD 13) à vontade por 1 hora ao beber.",
    "descricao": "Ao beber esta poção turva, você pode conjurar *Amizade Animal* (CD 13 para evitar) à vontade por 1 hora."
  },
  {
    "nome": "Poção de Clarividência",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede o efeito da magia Clarividência por 10 minutos.",
    "descricao": "Ao beber esta poção cintilante, você adquire o efeito da magia *Clarividência* por 10 minutos."
  },
  {
    "nome": "Poção de Compreensão",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede os benefícios da magia Compreender Idiomas por 1 hora.",
    "descricao": "Ao beber esta poção aromática, você adquire os benefícios da magia *Compreender Idiomas* por 1 hora."
  },
  {
    "nome": "Poção de Cura",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raridade Variável",
    "raridade": "Raridade Variável",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Recupera Pontos de Vida ao beber ou aplicar em outra criatura: Comum (2d4+2), Maior (4d4+4), Superior (8d4+8) ou Suprema (10d4+20).",
    "descricao": "Você recupera Pontos de Vida ao beber esta poção vermelha translúcida:\n- **Cura (Comum):** 2d4 + 2 Pontos de Vida\n- **Maior (Incomum):** 4d4 + 4 Pontos de Vida\n- **Superior (Raro):** 8d4 + 8 Pontos de Vida\n- **Suprema (Muito Raro):** 10d4 + 20 Pontos de Vida"
  },
  {
    "nome": "Poção de Escalada",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Deslocamento de Escalada igual ao seu deslocamento e Vantagem em testes de Atletismo para escalar por 1 hora.",
    "descricao": "Ao beber esta poção marrom espessa, você adquire um Deslocamento de Escalada igual ao seu Deslocamento e tem Vantagem em testes de Força (Atletismo) para escalar por 1 hora."
  },
  {
    "nome": "Poção de Força de Gigante",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raridade Variável",
    "raridade": "Raridade Variável",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Muda temporariamente o seu valor de Força por 1 hora: Colina (21), Pedra/Gelo (23), Fogo (25), Nuvens (27) ou Tempestade (29).",
    "descricao": "Ao beber esta poção transparente com substância flutuante, seu valor de Força muda por 1 hora conforme o tipo de gigante:\n- Colina: Força 21 (Incomum)\n- Pedra/Gelo: Força 23 (Raro)\n- Fogo: Força 25 (Muito Raro)\n- Nuvens: Força 27 (Muito Raro)\n- Tempestade: Força 29 (Lendário)"
  },
  {
    "nome": "Poção de Heroísmo",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede 10 Pontos de Vida Temporários e os efeitos da magia Bênção por 1 hora.",
    "descricao": "Ao beber esta poção azul-marinho cintilante, você ganha 10 Pontos de Vida Temporários e os efeitos da magia *Bênção* por 1 hora (sem requerer concentração)."
  },
  {
    "nome": "Poção de Invisibilidade",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede a condição Invisível por 1 hora (encerrada caso realize um ataque ou conjure uma magia).",
    "descricao": "Ao beber este líquido perfeitamente transparente, você adquire a condição Invisível por 1 hora. A condição termina mais cedo se você realizar uma jogada de ataque ou conjurar uma magia."
  },
  {
    "nome": "Poção de Invisibilidade Maior",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede a condição Invisível por 1 minuto sem quebrar ao atacar ou conjurar magias.",
    "descricao": "Ao beber este líquido cintilante, você adquire a condição Invisível por 1 minuto. Ao contrário da invisibilidade comum, atacar ou conjurar magias não quebra este efeito."
  },
  {
    "nome": "Poção de Invulnerabilidade",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Resistência a todos os tipos de dano por 1 minuto.",
    "descricao": "Ao beber este líquido xaroposo reluzente, você ganha Resistência a todos os tipos de dano por 1 minuto."
  },
  {
    "nome": "Poção de Ler Mentes",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede o efeito da magia Detectar Pensamentos (CD 13) por 1 minuto.",
    "descricao": "Ao beber este líquido púrpura luminescente, você adquire o efeito da magia *Detectar Pensamentos* (CD 13 para evitar) por 1 minuto."
  },
  {
    "nome": "Poção de Longevidade",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Reduz a sua idade biológica em 1d6+1 anos (10% de chance cumulativa de envelhecer 1d6+1 anos em usos repetidos).",
    "descricao": "Ao beber esta poção âmbar reluzente, sua idade física reduz em 1d6 + 1 anos (mínimo 13 anos). Cada poção adicional bebida tem 10% cumulativo de chance de falhar e envelhecer você em 1d6 + 1 anos em vez de rejuvenescer."
  },
  {
    "nome": "Poção de Pugilismo",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ataques Desarmados causam 1d6+Força de dano e têm bônus de +1 nas jogadas de ataque e dano por 1 hora.",
    "descricao": "Ao beber este tônico efervescente, seus Ataques Desarmados causam 1d6 + modificador de Força de dano e você recebe um bônus de +1 em jogadas de ataque e dano com eles por 1 hora."
  },
  {
    "nome": "Poção de Resistência",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Resistência a um tipo de dano específico por 1 hora (Ácido, Fogo, Frio, Elétrico, etc.).",
    "descricao": "Ao beber esta poção, você ganha Resistência a um determinado tipo de dano por 1 hora (Ácido, Elétrico, Energético, Fogo, Frio, Necrótico, Psíquico, Radiante, Trovejante ou Veneno)."
  },
  {
    "nome": "Poção de Respirar na Água",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite respirar debaixo d'água por 1 hora.",
    "descricao": "Ao beber este líquido verde-azulado, você pode respirar debaixo d'água por 1 hora."
  },
  {
    "nome": "Poção de Velocidade",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede o efeito da magia Velocidade por 1 minuto (sem requerer concentração).",
    "descricao": "Ao beber esta poção amarela efervescente com raios estalando, você adquire o efeito da magia *Velocidade* por 1 minuto sem requerer Concentração."
  },
  {
    "nome": "Poção de Vitalidade",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Remove todos os níveis de Exaustão, cura todas as doenças e venenos, e maximiza a cura de Dados de Vida pelas próximas 24 horas.",
    "descricao": "Ao beber esta poção rubi brilhante, remove todos os seus níveis de Exaustão, cura qualquer doença ou veneno, e você maximiza qualquer recuperação de Pontos de Vida com Dados de Vida durante as próximas 24 horas."
  },
  {
    "nome": "Poção de Voo",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Deslocamento de Voo igual ao seu deslocamento e capacidade de pairar por 1 hora.",
    "descricao": "Ao beber esta poção límpida com nuvens rodopiantes dentro, você adquire um Deslocamento de Voo igual ao seu Deslocamento e pode pairar no ar por 1 hora."
  },
  {
    "nome": "Poção do Amor",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Fica Enfeitiçado pela primeira criatura que vir nos próximos 10 minutos por 1 hora, considerando-a seu amor verdadeiro.",
    "descricao": "A criatura que beber este líquido rosa adquire a condição Enfeitiçado pela primeira criatura que avistar nos próximos 10 minutos, considerando-a como seu amor verdadeiro por 1 hora."
  },
  {
    "nome": "Poção do Crescimento",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede o efeito de Aumentar da magia Aumentar/Reduzir por 1d4 horas (+1d4 no dano de armas).",
    "descricao": "Ao beber esta poção, seu tamanho duplica e seu peso é multiplicado por oito como no efeito Aumentar da magia *Aumentar/Reduzir* por 1d4 horas (+1d4 no dano de armas e Vantagem em testes de Força)."
  },
  {
    "nome": "Poção do Encolhimento",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede o efeito de Reduzir da magia Aumentar/Reduzir por 1d4 horas.",
    "descricao": "Ao beber esta poção, seu tamanho é reduzido pela metade e seu peso é dividido por oito como no efeito Reduzir da magia *Aumentar/Reduzir* por 1d4 horas."
  },
  {
    "nome": "Poção Falsa",
    "tipo": "Poção",
    "subtipo": "",
    "tipo_linha": "Poção, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Assemelha-se a uma poção mágica benéfica, mas não produz nenhum efeito mágico ao ser consumida.",
    "descricao": "Esta poção parece idêntica em cor, cheiro e sabor a uma poção mágica genuína, mas é completamente inerte e não produz qualquer efeito benéfico."
  },
  {
    "nome": "Poço dos Mundos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pano circular de 1,8 m que se abre em um portal bidirecional para um plano de existência aleatório ou escolhido.",
    "descricao": "Desdobrar este tecido circular preto de 1,8 m de diâmetro abre um portal bidirecional ligando o local atual a um plano de existência diferente do multiverso."
  },
  {
    "nome": "Pote de Ferro",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Frasco de ferro com runas de latão capaz de aprisionar qualquer criatura de outro plano de existência (CD 17 Sab) sob seu comando.",
    "descricao": "Permite aprisionar uma criatura extraplanar a até 18 m (salvaguarda de Sabedoria CD 17). Ao destampar, a criatura obedece aos seus comandos por 1 hora ou até você morrer."
  },
  {
    "nome": "Pote do Despertar",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ao plantar um arbusto comum nele por 30 dias, o arbusto se transforma em um Arbusto Desperto aliado.",
    "descricao": "Ao plantar um arbusto comum neste vaso de argila de 4,5 kg por 30 dias e regá-lo, o vaso se quebra e o arbusto se transforma em um **Arbusto Desperto** aliado leal que entende seus comandos."
  }
];
