module.exports = [
  {
    "nome": "Faixas de Ferro de Bilarro",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Esfera de ferro arremessável (+7 ataque à distância) que se expande para aprisionar uma criatura Grande ou menor (Contido).",
    "descricao": "Arremessada a até 18 m (+7 no ataque), expande-se prendendo uma criatura Grande ou menor com a condição Contido (Força Atletismo CD 20 para escapar)."
  },
  {
    "nome": "Ferraduras de Velocidade",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Aumentam o deslocamento de um cavalo ou montaria similar em +9 metros.",
    "descricao": "Estas ferraduras vêm em um conjunto de quatro. Enquanto todas as quatro estiverem calçadas nos cascos de um cavalo ou criatura similar, elas aumentam o Deslocamento da criatura em 9 metros."
  },
  {
    "nome": "Ferraduras de Zéfiro",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permitem que a montaria flutue 10 cm acima do solo ou líquidos, ignorando terreno difícil e sem deixar pegadas.",
    "descricao": "Permitem que a montaria flutue 10 cm acima de qualquer superfície (chão, água, lava), ignorando Terreno Difícil e sem deixar pegadas ou rastros."
  },
  {
    "nome": "Flauta Atormentadora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para tocar uma melodia aterrorizante que impõe a condição Amedrontado em criaturas a até 9 m (CD 15 Sab).",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga para tocar uma melodia horripilante forçando criaturas a até 9 m a realizarem salvaguarda de Sabedoria CD 15 ou adquirem a condição Amedrontado por 1 minuto."
  },
  {
    "nome": "Flauta dos Esgotos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para invocar e controlar enxames de ratos como aliados com teste de Atuação CD 10.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Com teste de Carisma (Atuação) CD 10, convoca de 1 a 3 Enxames de Ratos que obedecem a comandos telepáticos simples."
  },
  {
    "nome": "Fortaleza Instantânea de Daern",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Cubo de metal que cresce instantaneamente em uma torre fortaleza quadrada de 6x6 m e 9 m de altura causando 10d10 contundente a criaturas no espaço.",
    "descricao": "Cubo de 2,5 cm que se expande em uma torre fortificada de adamantina de 6x6 m de base e 9 m de altura. Criaturas no espaço empurradas sofrem 10d10 dano Contundente (CD 15 Des). A fortaleza tem CA 20, 200 PV e portas trancadas magicamente."
  },
  {
    "nome": "Garra Silvestre",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ataques desarmados recebem +1 em ataque e dano e causam dano Mágico Cortante ou Perfurante à escolha.",
    "descricao": "Este item de tatuagem mágica ou amuleto confere um bônus de +1 nas jogadas de ataque e dano de Ataques Desarmados, permitindo causar dano Cortante ou Perfurante em vez de contundente."
  },
  {
    "nome": "Garrafa da Água Infinita",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Garrafa mágica que jorra água potável ou salgada em quatro fluxos: Gota (1 L), Fonte (19 L), Jato (114 L) ou Gêiser (114 L em cone, 1d4 contundente e Caído).",
    "descricao": "Produz água doce ou salgada ilimitada por comando de voz:\n- **Gota:** 1 litro por minuto.\n- **Fonte:** 19 litros por minuto.\n- **Jato:** 114 litros por minuto.\n- **Gêiser:** 114 litros em jato de 9 m causando 1d4 dano Contundente e derrubando o alvo Caído (CD 13 Força)."
  },
  {
    "nome": "Garrafa do Fumacê Eterno",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Despeja fumaça densa cobrindo 18 m de raio em 1 minuto e expandindo até 36 m a cada minuto subsequente (Área Fortemente Obscurecida).",
    "descricao": "Ao ser destampada, libera fumaça espessa criando Área Fortemente Obscurecida em 18 m de raio em 1 minuto, crescendo 3 m por minuto até 36 m. Fechar com a rolha interrompe a fumaça."
  },
  {
    "nome": "Garrafa Ifriti",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Garrafa de latão contendo um Ifriti aprisionado que pode atacá-lo, servi-lo lealmente por 1 hora ou conceder três magias de Desejo.",
    "descricao": "Destampá-la liberta um **Ifriti**. O Mestre rola 1d100 para determinar o resultado:\n- 01-10: O Ifriti ataca você imediatamente por 5 rodadas e depois parte.\n- 11-90: O Ifriti serve você lealmente por até 1 hora ou até você morrer.\n- 91-100: O Ifriti concede a você três conjurações de *Desejo* e se liberta para sempre."
  },
  {
    "nome": "Gema da Claridade",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 50 cargas para emitir luz (1 carga), facho ofuscante (2 cargas, CD 15 Con contra Cego) ou raio cegante em 9 m (3 cargas).",
    "descricao": "Possui 50 cargas.\n- 1 carga: Luz Plena 9 m e Meia-luz 9 m.\n- 2 cargas: Cone de 18 m força salvaguarda CD 15 Con ou fica Cego por 1 minuto.\n- 3 cargas: Raio de 9 m cega todas as criaturas que falharem na CD 15 Con por 1 minuto."
  },
  {
    "nome": "Gema da Visão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para conceder Visão Verdadeira de 36 metros por 10 minutos ao olhar através dela.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga para obter Visão Verdadeira de 36 metros por 10 minutos ao olhar através da gema."
  },
  {
    "nome": "Gema Elemental",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Gema mágica consumível que conjura Conjurar Elemental sem Concentração ao ser quebrada (Ar, Fogo, Terra ou Água).",
    "descricao": "Ao ser esmagada no chão como ação Usar Magia, invoca um Elemental sob seu controle por 1 hora sem requerer Concentração (Diamante Amarelo: Ar; Esmeralda: Água; Rubi: Fogo; Safira: Terra)."
  },
  {
    "nome": "Grilhões Dimensionais",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Algemas mágicas que impedem completamente teleporte, viagem planar e movimento extradimensional da criatura aprisionada.",
    "descricao": "Prendem criatura Pequena, Média ou Grande. A criatura algemada não pode se teleportar, viajar entre planos ou acessar espaços extradimensionais (Atletismo CD 30 a cada 30 dias para escapar)."
  },
  {
    "nome": "Haste Retrátil",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Haste de metal de 30 cm que se estende até 3 metros ou retrai ao pressionar o botão.",
    "descricao": "Com uma Ação Bônus ao pressionar o botão, esta haste de metal expande-se até 3 metros de comprimento ou se retrai de volta para 30 cm."
  },
  {
    "nome": "Incensário de Controlar Elementais do Ar",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite invocar um Elemental do Ar obediente por até 1 hora 1x ao dia ao queimar incenso.",
    "descricao": "Ao queimar incenso nele por 1 minuto, invoca um **Elemental do Ar** obediente por 1 hora (1x ao dia)."
  },
  {
    "nome": "Insígnia da Pena de Quaal",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pena mágica consumível com efeito único (Árvore de 18 m, Barco a Remo de 24h, Cisne voador, Chicote animado ou Âncora imovível).",
    "descricao": "Pena mágica de uso único ativada com ação Usar Magia:\n- **Árvore:** Brota um carvalho de 18 m de altura instantaneamente.\n- **Barco a Remo:** Cria barco a remo por 24 horas.\n- **Cisne:** Cria cisne voador gigante para transporte rápido por 24h.\n- **Chicote:** Flutua e ataca como arma mágica (+9 atq, 1d6+5 de força).\n- **Âncora:** Prende embarcação no lugar por 24h suportando tempestades."
  },
  {
    "nome": "Instrumento Musical de Escrita",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Faz aparecer palavras brilhantes no ar descrevendo notas, sentimentos ou rimas enquanto tocado.",
    "descricao": "Enquanto você toca este instrumento musical, pode fazer com que pequenas frases ou palavras poéticas e brilhantes apareçam no ar ao seu redor."
  },
  {
    "nome": "Instrumento Musical de Ilusões",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Cria pequenas ilusões visuais inofensivas (folhas, estrelas, chamas sem calor) a até 4,5 metros ao ser tocado.",
    "descricao": "Enquanto toca o instrumento, cria pequenas imagens visuais inofensivas a até 4,5 m de você (pétalas caindo, estrelas brilhantes, figuras dançantes de meia-luz)."
  },
  {
    "nome": "Instrumento Musical dos Bardos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raridade Variável (Requer Sintonização por um Bardo)",
    "raridade": "Raridade Variável",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Bardo",
    "resumo": "Instrumento lendário para Bardos: impõe Desvantagem em salvaguardas contra feitiços de charme e conjura vasto repertório diário de magias.",
    "descricao": "Instrumento requintado de bardos lendários. Impõe Desvantagem na salvaguarda de alvos enfeitiçados por suas magias. Permite conjurar magias universais diárias (*Invisibilidade*, *Levitação*, *Voo*, *Proteção contra o Bem e Mal*) além de magias exclusivas por modelo:\n- **Alaúde Anstruth (Muito Raro):** Muralha de Espinhos, Controlar o Clima, Curar Ferimentos em Massa.\n- **Bandolim Canaith (Raro):** Dissipar Magia, Curar Ferimentos 3º, Proteção contra Energia.\n- **Citara Doss (Incomum):** Amizade Animal, Proteção contra Veneno, Feitiço.\n- **Harpa Cli (Muito Raro):** Confusão, Controlar os Ventos, Muralha de Fogo.\n- **Harpa Ollamh (Lendário):** Tempestade de Fogo, Ataque Visual, Ressurreição.\n- **Lira Fochlucan (Incomum):** Fogo das Fadas, Falar com Animais, Falar com Plantas.\n- **Lira Mac-Fuirmhidh (Incomum):** Névoa Obscurecente, Pele-casca, Queda Suave."
  },
  {
    "nome": "Jarro Alquímico",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Produz líquidos diariamente por comando de voz (Ácido, Cerveja, Mel, Óleo, Veneno Básico, Água Doce, Vinho ou Maionese).",
    "descricao": "Produz líquidos com uma ação Usar Magia 1x ao dia:\n- Ácido (250 ml)\n- Água Doce (30 L) ou Salgada (45 L)\n- Cerveja (15 L) ou Vinho (4 L)\n- Mel (4 L) ou Maionese (8 L)\n- Óleo (4 L)\n- Veneno Básico (120 ml)\n- Vinagre (8 L)"
  },
  {
    "nome": "Lâmina da Sorte",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive ou Rapieira), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Espada +1 (+1 CA e salvaguardas), permite rolar novamente qualquer teste/ataque 1x ao dia e contém 1d4-1 conjurações de Desejo.",
    "descricao": "Concede +1 em jogadas de ataque e dano, além de +1 na CA e em todas as salvaguardas. Possui a propriedade *Sorte*: permite jogar novamente qualquer jogada de ataque, teste ou salvaguarda 1x ao dia. Contém 1d4 - 1 conjurações de *Desejo*."
  },
  {
    "nome": "Lâmina Solar",
    "tipo": "Arma",
    "subtipo": "Espada Longa",
    "tipo_linha": "Arma (Espada Longa), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Punho sem lâmina física que projeta lâmina de pura luz solar (+2 ataque/dano, Acuidade, dano Radiante e +1d8 extra contra mortos-vivos).",
    "descricao": "Com uma Ação Bônus, emite lâmina de luz solar pura. Possui as propriedades Acuidade e Versátil. Concede +2 em jogadas de ataque e dano, causando dano Radiante em vez de cortante, e causa +1d8 pontos de dano Radiante adicionais contra Mortos-Vivos. Emite Luz Plena de 4,5 a 9 m."
  },
  {
    "nome": "Laminegra",
    "tipo": "Arma",
    "subtipo": "Espada Grande",
    "tipo_linha": "Arma (Espada Grande), Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Artefato maligno +3 senciente que devora almas de criaturas mortas, cura o usuário e concede imunidade a Enfeitiçado e Amedrontado.",
    "descricao": "Espada Grande senciente de obsidiana forjada para ceifar almas. Concede +3 em ataque e dano, imunidade a Enfeitiçado e Amedrontado e telepatia. Ao matar criatura viva, devora sua alma e concede PV temporários iguais à metade dos PV máximos da vítima. Devora a alma do portador caso não se alimente de almas regularmente."
  },
  {
    "nome": "Lanterna Reveladora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Lanterna com óleo que emite raio de luz revelando criaturas e objetos invisíveis a até 9 metros.",
    "descricao": "Enquanto acesa com óleo comum, projeta cone de Luz Plena de 9 m que revela qualquer criatura ou objeto com a condição Invisível dentro do raio iluminado."
  },
  {
    "nome": "Leque do Vento",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite conjurar Lufada de Vento (CD 13) ao abanar o leque (20% de chance de rasgar ao usar repetidamente no mesmo dia).",
    "descricao": "Permite conjurar *Lufada de Vento* (CD 13 para evitar) com uma ação Usar Magia. Usar repetidas vezes antes do amanhecer tem 20% cumulativo de chance de destruir o leque."
  },
  {
    "nome": "Língua Flamejante",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive ou Rapieira), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ação Bônus para inflamar a lâmina com fogo ardente, causando +2d6 dano Ígneo em cada acerto e iluminando 12 m.",
    "descricao": "Com uma Ação Bônus ao pronunciar a palavra de comando, a lâmina irrompe em chamas causando 2d6 pontos de dano Ígneo adicionais em cada acerto e emitindo Luz Plena em 12 metros."
  },
  {
    "nome": "Livro das Trevas Profanas",
    "tipo": "Item Maravilhoso",
    "subtipo": "Artefato",
    "tipo_linha": "Item Maravilhoso, Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Criatura Maligna",
    "resumo": "Artefato supremo do mal: +2 em atributo primário (máx 24), Vantagem em Arcanismo maligno, Aura de Escuridão e magias necróticas devastadoras.",
    "descricao": "O livro mais perverso do multiverso. Permite ler por 80 horas para ganhar +2 em um atributo (máx 24) e 1 talento épico. Concede conjuração de magias necróticas sombrias, aura de horror e corrupção inexorável sobre quem o folhear sem ser perverso."
  },
  {
    "nome": "Livro de Magias Durável",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Livro de magias imune a dano de fogo, água e intempéries climáticas.",
    "descricao": "Este livro de magias de couro reforçado não pode ser danificado por fogo ou água, e é imune a deterioração comum pelo tempo."
  },
  {
    "nome": "Livro dos Feitos Sublimes",
    "tipo": "Item Maravilhoso",
    "subtipo": "Artefato",
    "tipo_linha": "Item Maravilhoso, Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Criatura Boa",
    "resumo": "Artefato supremo da bondade e justiça: +2 em Sabedoria/Carisma (máx 24), Halo Sagrado de proteção contra o mal, Cura Suprema e magias divinas.",
    "descricao": "Compêndio divino supremo da luz. Concede aumento permanente de +2 em atributo mental (máx 24), Halo Sagrado que emite luz plena e confere Vantagem contra demônios e mortos-vivos, além de permitir conjurar *Cura Completa*, *Ressurreição Suprema* e *Coluna de Chamas*."
  },
  {
    "nome": "Loriga de Escamas Dracônicas",
    "tipo": "Armadura",
    "subtipo": "Loriga de Escamas",
    "tipo_linha": "Armadura (Loriga de Escamas), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Armadura +1 na CA, Vantagem contra sopros e presença aterradora de dragões, Resistência ao tipo de dano do dragão e sentido de dragões a até 48 km.",
    "descricao": "Concede +1 na Classe de Armadura, Vantagem em salvaguardas contra o Sopro e Presença Aterradora de Dragões, e Resistência ao tipo de dano associado à cor das escamas (Ácido, Fogo, Frio, Elétrico ou Veneno). Permite detectar a direção do dragão mais próximo em 48 km 1x ao dia."
  },
  {
    "nome": "Lunâmina",
    "tipo": "Arma",
    "subtipo": "Espada Longa",
    "tipo_linha": "Arma (Espada Longa), Lendário (Requer Sintonização por um Elfo)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Elfo ou Meio-Elfo",
    "resumo": "Herança élfica milenar +1 a +3 na CA/ataque, contendo runas de ancestrais que concedem poderes únicos (Acuidade, dano extra, magias e invocações).",
    "descricao": "Lendária espada élfica passada entre gerações com runas gravadas por cada portador anterior. Concede de +1 a +3 em ataque/dano, Acuidade, poderes adicionais (como crítico 19-20, dano extra radiante, anel de armazenamento ou invocar guerreiro espiritual)."
  },
  {
    "nome": "Luvas da Ladinagem",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ficam invisíveis nas mãos e concedem um bônus de +5 em testes de Prestidigitação e Ferramentas de Ladrão.",
    "descricao": "Estas luvas tornam-se invisíveis ao serem vestidas. Concedem um bônus de +5 em testes de Destreza (Prestidigitação) e testes de Destreza com Ferramentas de Ladrão para arrombar fechaduras ou desarmar armadilhas."
  },
  {
    "nome": "Luvas de Apanhar Projéteis",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Reação para reduzir o dano de ataques com armas à distância em 1d10 + modificador de Destreza (se reduzir a 0, apanha o projétil).",
    "descricao": "Ao ser atingido por um ataque com arma à distância, você pode executar uma Reação para reduzir o dano em 1d10 + modificador de Destreza. Se o dano for reduzido a 0, você apanha o projétil na mão se tiver uma mão livre."
  },
  {
    "nome": "Luvas de Natação e Escalada",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Escalar e nadar não custa movimento adicional; bônus de +5 em testes de Atletismo para nadar ou escalar.",
    "descricao": "Nadar ou escalar não custa movimento extra a você. Além disso, você tem um bônus de +5 em testes de Força (Atletismo) realizados para nadar ou escalar."
  },
  {
    "nome": "Maça da Destruição",
    "tipo": "Arma",
    "subtipo": "Maça",
    "tipo_linha": "Arma (Maça), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Maça +1 (+3 contra Constructos); acerto crítico contra Constructo causa +2d6 contundente e pode destruí-lo se tiver <=25 PV.",
    "descricao": "Você adquire um bônus de +1 em jogadas de ataque e dano (+3 contra Constructos). Em acerto crítico contra Constructo, causa +2d6 contundente e o alvo é destruído instantaneamente se tiver 25 PV ou menos."
  },
  {
    "nome": "Maça da Disrupção",
    "tipo": "Arma",
    "subtipo": "Maça",
    "tipo_linha": "Arma (Maça), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Causa +2d6 dano Radiante contra Ínferos e Mortos-Vivos; se o alvo tiver <=25 PV após o acerto, deve passar em Sabedoria CD 15 ou é desintegrado.",
    "descricao": "Ao atingir um Ínfero ou Morto-Vivo, causa 2d6 pontos de dano Radiante adicionais. Se o alvo ficar com 25 PV ou menos, deve passar em salvaguarda de Sabedoria CD 15 ou é destruído instantaneamente. Emite luz radiante."
  },
  {
    "nome": "Maça do Terror",
    "tipo": "Arma",
    "subtipo": "Maça",
    "tipo_linha": "Arma (Maça), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para emitir onda de terror de 9 m impondo a condição Amedrontado e fuga forçada (CD 15 Sab).",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga para emitir uma onda aterrorizante em raio de 9 metros (salvaguarda de Sabedoria CD 15 ou adquire a condição Amedrontado por 1 minuto, gastando turnos para fugir)."
  },
  {
    "nome": "Machado do Carrasco",
    "tipo": "Arma",
    "subtipo": "Machado Grande",
    "tipo_linha": "Arma (Machado Grande), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Machado +1 (+2d6 cortante em humanoides); Acerto Crítico em humanoide causa +4d6 cortante adicional.",
    "descricao": "Concede +1 em jogadas de ataque e dano. Causa 2d6 pontos de dano Cortante adicionais contra Humanoides. Ao obter Acerto Crítico contra Humanoide, causa 4d6 de dano Cortante adicionais."
  },
  {
    "nome": "Machado dos Senhores Anões",
    "tipo": "Arma",
    "subtipo": "Machado de Batalha",
    "tipo_linha": "Arma (Machado de Batalha), Artefato (Requer Sintonização por um Anão)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Anão",
    "resumo": "Machado +3 com arremesso mágico (18/54 m), crítico 19-20 (+3d6 dano), Visão no Escuro 36 m, imunidade a veneno e conjuração de golens e terremotos.",
    "descricao": "Relíquia anã suprema. Concede +3 em ataque e dano, propriedade Arremesso 18/54 m retornando à mão. Crítico 19-20 causando +3d6 de dano. Imunidade a veneno, Visão no Escuro 36 m e conjura *Moldar Rochas*, *Muralha de Pedra*, *Terremoto* e invoca um Golem de Pedra aliado."
  },
  {
    "nome": "Machado-Berserker",
    "tipo": "Arma",
    "subtipo": "Machado de Guerra ou Machado Grande",
    "tipo_linha": "Arma (Machado de Guerra ou Machado Grande), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Machado +1 que concede +1 PV máximo por nível; amaldiçoado induzindo fúria incontrolável ao sofrer dano (CD 15 Sab).",
    "descricao": "Concede +1 em jogadas de ataque e dano e aumenta seu máximo de PV em 1 por nível de personagem.\n\n***Maldição.*** Ao sofrer dano em combate, deve passar em salvaguarda de Sabedoria CD 15 ou entra em Fúria Berserker atacando a criatura mais próxima (amiga ou inimiga)."
  },
  {
    "nome": "Manoplas de Poder do Ogro",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Seu valor de Força torna-se 19 enquanto calçar estas manoplas (sem efeito se já for 19 ou maior).",
    "descricao": "Sua pontuação de Força se torna 19 enquanto você usar estas manoplas de metal reforçado. Elas não têm efeito se sua Força já for 19 ou superior."
  },
  {
    "nome": "Manto da Arraia",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite respirar debaixo d'água e concede Deslocamento de Natação de 18 metros com o capuz puxado.",
    "descricao": "Com o capuz puxado, você pode respirar debaixo d'água e ganha um Deslocamento de Natação de 18 metros."
  },
  {
    "nome": "Manto da Natureza",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização por um Druida ou Guardião)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Druida ou Guardião",
    "resumo": "Foco de conjuração para druidas e guardiões; permite Esconder-se como Ação Bônus em Meia-luz mesmo sendo observado.",
    "descricao": "Serve como foco de conjuração de Druida ou Guardião. Enquanto estiver em Meia-luz ou escuridão, permite usar a ação Esconder-se como Ação Bônus mesmo sob observação direta."
  },
  {
    "nome": "Manto das Asas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Transforma-se em asas de morcego ou pássaro concedendo Deslocamento de Voo de 18 metros e Vantagem em Furtividade.",
    "descricao": "Com uma Ação Bônus ao segurar as bordas do manto, ele transforma-se em um par de asas concedendo Deslocamento de Voo de 18 metros e Vantagem em testes de Destreza (Furtividade)."
  },
  {
    "nome": "Manto de Invisibilidade",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite puxar o capuz como ação Usar Magia para ficar Invisível por até 2 horas diárias (não quebra ao atacar ou conjurar).",
    "descricao": "Puxar o capuz como ação Usar Magia concede a condição Invisível por até 2 horas de uso diário (fracionável). A invisibilidade não é encerrada ao atacar ou conjurar magias."
  },
  {
    "nome": "Manto de Proteção",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede um bônus de +1 na Classe de Armadura e em todas as salvaguardas.",
    "descricao": "Você recebe um bônus de +1 na Classe de Armadura e em todas as salvaguardas enquanto estiver usando este manto elegante."
  },
  {
    "nome": "Manto de Resistência à Magia",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede Vantagem em todas as salvaguardas contra magias.",
    "descricao": "Você adquire Vantagem em salvaguardas contra magias enquanto estiver usando este manto com runas tecidas."
  },
  {
    "nome": "Manto do Morcego",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Vantagem em Furtividade, Deslocamento de Voo de 12 m na penumbra/escuridão e permite transformar-se em Morcego (Polimorfia).",
    "descricao": "Concede Vantagem em testes de Furtividade. Em Meia-luz ou Escuridão, segurar as pontas concede Voo de 12 metros. Permite conjurar *Polimorfia* em si mesmo para transformar-se em um **Morcego** (mantendo Inteligência, Sabedoria e Carisma) 1x ao dia."
  },
  {
    "nome": "Manual de Rapidez nas Ações",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estudo por 48 horas aumenta o valor e o limite máximo de Destreza em +2 permanentemente.",
    "descricao": "Contém memórias e exercícios de agilidade. Após 48 horas de estudo em 6 dias ou menos, seu valor de Destreza aumenta em 2 e seu valor máximo para esse atributo passa a ser 22. O livro perde sua magia por 1 século."
  },
  {
    "nome": "Manual de Saúde Corporal",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estudo por 48 horas aumenta o valor e o limite máximo de Constituição em +2 permanentemente.",
    "descricao": "Após 48 horas de estudo em 6 dias ou menos, seu valor de Constituição aumenta em 2 e seu valor máximo para esse atributo passa a ser 22. O livro perde sua magia por 1 século."
  },
  {
    "nome": "Manual dos Exercícios Benéficos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estudo por 48 horas aumenta o valor e o limite máximo de Força em +2 permanentemente.",
    "descricao": "Após 48 horas de estudo em 6 dias ou menos, seu valor de Força aumenta em 2 e seu valor máximo para esse atributo passa a ser 22. O livro perde sua magia por 1 século."
  },
  {
    "nome": "Manual dos Golens",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Tratado detalhado que permite a um conjurador construir um Golem aliado leal (Argila, Carne, Ferro ou Pedra).",
    "descricao": "Guia de construção de constructos para conjuradores com pelo menos dois espaços de 5º círculo. Leva de 30 a 120 dias de trabalho contínuo e custo em ouro correspondente para forjar o Golem escolhido, que serve com lealdade eterna."
  },
  {
    "nome": "Martelo Arremessável dos Anões",
    "tipo": "Arma",
    "subtipo": "Martelo de Guerra",
    "tipo_linha": "Arma (Martelo de Guerra), Muito Raro (Requer Sintonização por um Anão)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Anão",
    "resumo": "Martelo +3 com Arremesso 6/18 m retornando à mão; ao ser arremessado, causa +1d8 contundente extra (+2d8 se o alvo for Gigante).",
    "descricao": "Concede +3 em ataque e dano. Adquire a propriedade Arremesso (6/18 m) e retorna voando para a mão. Em ataques arremessados bem-sucedidos, causa 1d8 pontos de dano Contundente adicionais (ou 2d8 contra Gigantes)."
  },
  {
    "nome": "Martelo do Trovão",
    "tipo": "Arma",
    "subtipo": "Martelo de Guerra",
    "tipo_linha": "Arma (Martelo de Guerra), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização com Manoplas do Ogro e Cinturão de Gigante",
    "resumo": "Martelo +1 (+4 Força até máx 30); se sintonizado com Manoplas e Cinturão, torna-se +3, mata Gigantes no resultado 20 (CD 17 Con) e possui estrondo sônico arremessável de 9 m (Atordoado).",
    "descricao": "Concede +1 em ataque e dano e +4 no valor de Força (máx 30).\nSe sintonizado em conjunto com *Manoplas de Poder do Ogro* e *Cinturão de Força de Gigante*:\n- O bônus passa a ser +3.\n- No resultado 20 natural contra um Gigante, ele deve passar em salvaguarda de Constituição CD 17 ou morre instantaneamente.\n- Arremesso 6/18 m que explode em estrondo sônico forçando salvaguarda CD 17 Con ou criaturas em 9 m ficam Atordoadas até o início do seu próximo turno."
  },
  {
    "nome": "Matadora de Dragões",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Arma +1 (+3d6 de dano adicional contra qualquer criatura do tipo Dragão).",
    "descricao": "Você adquire um bônus de +1 em jogadas de ataque e dano realizadas com esta arma mágica. Ao atingir um Dragão com ela, a arma causa 3d6 pontos de dano adicionais do tipo de dano normal da arma."
  },
  {
    "nome": "Matadora de Gigantes",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Arma +1 (+2d6 de dano contra Gigantes e força o Gigante a passar em salvaguarda de Força CD 15 ou cai Caído).",
    "descricao": "Concede bônus de +1 em jogadas de ataque e dano. Ao atingir um Gigante, causa 2d6 pontos de dano adicionais e força o gigante a realizar salvaguarda de Força CD 15 ou é derrubado com a condição Caído."
  },
  {
    "nome": "Membro Protético",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Substitui perfeitamente um braço, perna, mão ou pé perdido, operando como o membro original.",
    "descricao": "Este item substitui um membro perdido (braço, perna, mão ou pé). Enquanto estiver sintonizado, funciona identicamente ao membro biológico original e não pode ser removido contra a sua vontade."
  },
  {
    "nome": "Mochila Prestativa de Heward",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Mochila de 3 compartimentos extradimensionais (até 250 kg total pesando sempre 2,5 kg) que entrega o item desejado no topo.",
    "descricao": "Possui 1 bolso central (200 kg) e 2 bolsos laterais (25 kg cada). Pesa sempre 2,5 kg. Qualquer item armazenado pode ser retirado instantaneamente no topo do compartimento."
  },
  {
    "nome": "Moeda Rival",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Moeda de prata que permite escolher voluntariamente cara ou coroa ao ser lançada.",
    "descricao": "Ao jogar esta moeda de prata para cima, você pode decidir mentalmente se ela cairá em cara ou coroa."
  },
  {
    "nome": "Munição Exterminadora",
    "tipo": "Arma",
    "subtipo": "Flecha, Virote ou Bala de Funda",
    "tipo_linha": "Arma (Qualquer Munição), Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Munição mágica sintonizada a um tipo de criatura: causa +6d10 dano Perfurante adicional em acertos.",
    "descricao": "Esta munição mágica é feita para destruir um tipo específico de criatura (Dragões, Ínferos, Mortos-Vivos, etc.). Ao atingir a criatura designada, causa 6d10 pontos de dano Perfurante adicionais. Torna-se não mágica após o impacto."
  },
  {
    "nome": "Munição Impactante",
    "tipo": "Arma",
    "subtipo": "Flecha, Virote ou Bala de Funda",
    "tipo_linha": "Arma (Qualquer Munição), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Causa +1d10 dano Energético e empurra o alvo 3 metros para trás ao acertar.",
    "descricao": "Ao atingir uma criatura, esta munição causa 1d10 pontos de dano Energético adicionais e empurra o alvo 3 metros em linha reta para longe de você."
  },
  {
    "nome": "Munição, +1, +2 ou +3",
    "tipo": "Arma",
    "subtipo": "Qualquer Munição",
    "tipo_linha": "Arma (Qualquer Munição), Incomum (+1), Raro (+2) ou Muito Raro (+3)",
    "raridade": "Incomum (+1), Raro (+2), Muito Raro (+3)",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede um bônus de +1, +2 ou +3 em jogadas de ataque e dano com a munição disparada.",
    "descricao": "Você adquire um bônus em jogadas de ataque e dano realizadas com esta munição mágica (+1 Incomum, +2 Raro, +3 Muito Raro). A magia se dissipa após atingir um alvo."
  }
];
