module.exports = [
  {
    "nome": "Adaga Peçonhenta",
    "tipo": "Arma",
    "subtipo": "Adaga",
    "tipo_linha": "Arma (Adaga), Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Você adquire um bônus de +1 em jogadas de ataque e dano e pode revestir a lâmina com veneno (2d10 veneno, CD 15 Con).",
    "descricao": "Você adquire um bônus de +1 em jogadas de ataque e dano realizadas com esta arma mágica.\n\nVocê pode executar uma Ação Bônus para revestir magicamente a lâmina com veneno. O veneno permanece por 1 minuto ou até que um ataque usando esta arma atinja uma criatura. Essa criatura deve ser bem-sucedida em uma salvaguarda de Constituição CD 15 ou sofre 2d10 pontos de dano Venenoso e tem a condição Envenenado por 1 minuto. A arma não pode ser usada deste modo novamente até o próximo amanhecer."
  },
  {
    "nome": "Alaúde de Batidas Estrondosas",
    "tipo": "Arma",
    "subtipo": "Clava",
    "tipo_linha": "Arma (Clava), Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Clava mágica que causa 2d8 pontos de dano Trovejante adicionais. Bardos podem usar Carisma em vez de Força ao cantar.",
    "descricao": "Este alaúde reforçado pode ser empunhado como uma Clava mágica que causa 2d8 pontos de dano Trovejante adicionais ao acertar.\n\n***Cante e Golpeie.*** Se você for um Bardo, pode usar seu modificador de Carisma em vez do modificador de Força ao realizar uma jogada de ataque corpo a corpo com o alaúde, desde que esteja cantando ou cantarolando durante o ataque."
  },
  {
    "nome": "Aljava de Ehlonna",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Aljava mágica com 3 compartimentos extradimensionais para flechas, azagaias e armas longas, sem pesar mais de 1 kg.",
    "descricao": "Cada um dos três compartimentos dessa aljava conecta-se a um espaço extradimensional que permite armazenar inúmeros itens sem pesar mais de 1 quilo. O compartimento mais curto pode conter até 60 Flechas, Virotes ou objetos similares. O compartimento médio comporta até 18 Azagaias ou objetos similares. O compartimento mais longo pode armazenar até 6 objetos longos, como arcos, Cajados ou Lanças.\n\nVocê pode sacar qualquer item da aljava como se estivesse pegando de uma aljava ou bainha comum."
  },
  {
    "nome": "Amuleto da Estilha Negra",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização por um Bruxo)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Bruxo",
    "resumo": "Foco de conjuração de Bruxo que permite tentar conjurar um truque desconhecido com teste de Arcanismo CD 10.",
    "descricao": "Este amuleto é formado a partir de um fragmento de material resiliente originário de um reino de outro mundo. Enquanto estiver usando-o, você adquire os seguintes benefícios.\n\n***Foco de Conjuração.*** Você pode usar o amuleto como um Foco de Conjuração para suas magias de Bruxo.\n\n***Magia Desconhecida.*** Como uma ação Usar Magia, você pode tentar conjurar um truque que não conhece. O truque deve estar na lista de magias do Bruxo e ter um tempo de conjuração de uma ação e você realiza um teste de Inteligência (Arcanismo) CD 10. Em caso de sucesso, você conjura a magia. Se falhar, a magia falha e a ação usada para conjurá-la é desperdiçada. Em ambos os casos, você não pode usar esta propriedade novamente até completar um Descanso Longo."
  },
  {
    "nome": "Amuleto da Saúde",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Sua Constituição é fixada em 19 enquanto usar este amuleto (sem efeito se já for 19 ou superior).",
    "descricao": "Sua Constituição é 19 enquanto usar este amuleto; se já for 19 ou superior, ele não tem efeito."
  },
  {
    "nome": "Amuleto de Proteção Contra Detecção e Localização",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Oculta o usuário aos efeitos de magias de Adivinhação e sensores mágicos de vidência.",
    "descricao": "Enquanto estiver usando este amuleto, você fica oculto aos efeitos de magias de Adivinhação. Você não pode ser alvo de tais magias ou ser percebido por sensores mágicos de vidência."
  },
  {
    "nome": "Amuleto Mecânico",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite usar um resultado 10 em vez de rolar o d20 em uma jogada de ataque 1x ao dia.",
    "descricao": "Este amuleto de cobre contém pequenas engrenagens interligadas e funciona com a magia de Mecânos, um plano de precisão mecânica. Ruídos fracos de tique-taque e zumbidos emanam vindos de dentro.\n\nAo realizar uma jogada de ataque enquanto utiliza o amuleto, você pode usar um 10 em vez de jogar um d20. Uma vez usada, esta propriedade não pode ser usada novamente até o próximo amanhecer."
  },
  {
    "nome": "Amuleto Planar",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar Transição Planar com teste de Arcanismo CD 15 (com risco de desvio para planos aleatórios em caso de falha).",
    "descricao": "Enquanto estiver usando este amuleto, você pode executar uma ação Usar Magia para nomear um local em outro plano de existência com o qual esteja familiarizado. Em seguida, realize um teste de Inteligência (Arcanismo) CD 15. Em caso de sucesso, você conjura *Transição Planar*. Se falhar, você e cada criatura e objeto em um raio de 4,5 metros viajam para um destino aleatório determinado ao jogar 1d100, conforme a tabela a seguir.\n\n| 1d100 | Destino |\n| :---- | :---- |\n| 01-60 | Local aleatório no plano nomeado |\n| 61-70 | Localização aleatória em um Plano Interno determinada pela jogada de 1d6: em um **1**, o Plano do Ar; em um **2**, o Plano da Terra; em um **3**, o Plano do Fogo; em um **4**, o Plano da Água; em um **5**, Faéria; em um **6**, o Sombral |\n| 71-80 | Localização aleatória em um Plano Externo determinada pela jogada de 1d8: em um **1**, Arbórea; em um **2**, Arcádia; em um **3**, as Terras Ferais; em um **4**, Bitopia; em um **5**, Elísio; em um **6**, Mecânos; em um **7**, Monte Celéstia; em um **8**, Ysgard |\n| 81-90 | Localização aleatória em um Plano Externo determinada pela jogada de 1d8: em um **1**, o Abismo; em um **2**, Aqueronte; em um **3**, Cárceri; em um **4**, Gehenna; em um **5**, Hades; em um **6**, Limbo; em um **7**, os Nove Infernos; em um **8**, Pandemônio |\n| 91-100 | Local aleatório no Plano Astral |"
  },
  {
    "nome": "Anel Afastador de Magias",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Vantagem em salvaguardas contra magias; anula magias de 7º círculo ou menor em sucesso e pode refleti-las com Reação.",
    "descricao": "Enquanto estiver usando este anel, você tem Vantagem em salvaguardas contra magias. Se você for bem-sucedido na salvaguarda contra uma magia de 7º círculo ou inferior, a magia não tem efeito sobre você. Se essa magia teve apenas você como alvo e não cria uma área de efeito, você pode executar uma Reação para desviar a magia de volta para o conjurador; o conjurador deve realizar uma salvaguarda contra a magia usando sua própria CD para evitar magia."
  },
  {
    "nome": "Anel Armazenador de Magias",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Armazena até 5 círculos de magias conjuradas nele para serem conjuradas posteriormente pelo usuário.",
    "descricao": "Este anel armazena magias conjuradas nele, contendo-as até que o usuário sintonizado as use. O anel pode armazenar até 5 círculos de magias de cada vez. Quando encontrado, o anel contém 1d6 - 1 círculos de magias armazenadas escolhidas pelo Mestre.\n\nQualquer criatura pode conjurar uma magia de 1º a 5º círculo no anel ao tocá-lo no momento em que a magia é conjurada. A magia não tem efeito, exceto por ser armazenada no anel. Se o anel não puder conter a magia, esta é gasta sem efeito. O círculo de espaço utilizado para conjurar a magia determina quanto espaço ela ocupa.\n\nEnquanto está usando o anel, você pode conjurar qualquer magia que esteja armazenada nele. A magia utiliza o círculo de espaço, CD para evitar, bônus de ataque mágico e atributo de conjuração do conjurador original, mas é considerada como se você a estivesse conjurando. A magia conjurada do anel não está mais armazenada nele, liberando espaço."
  },
  {
    "nome": "Anel da Livre Movimentação",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Terreno Difícil não custa movimento extra; magia não pode reduzir deslocamentos nem impor Contido ou Paralisado.",
    "descricao": "Enquanto estiver usando este anel, Terreno Difícil não custa movimento adicional a você. Além disso, a magia não pode reduzir nenhum de seus Deslocamentos nem impor a condição Contido ou Paralisado a você."
  },
  {
    "nome": "Anel das Estrelas Cadentes",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Conjura Luz e Luzes Dançantes à vontade; gasta cargas para criar Esferas de Relâmpago, Estrelas Cadentes e Fogo das Fadas.",
    "descricao": "Você pode conjurar *Luzes Dançantes* ou *Luz* a partir do anel.\n\nO anel tem 6 cargas e recupera 1d6 cargas gastas diariamente ao amanhecer. Você pode gastar as cargas do anel para usar as propriedades abaixo.\n\n***Esferas de Relâmpago.*** Você pode gastar 2 cargas como uma ação Usar Magia para criar até quatro esferas de relâmpago de 90 centímetros de diâmetro.\n\nCada esfera aparece em um espaço desocupado à sua vista a até 36 metros de distância. As esferas permanecem enquanto você mantiver a Concentração, até 1 minuto. Cada esfera projeta Meia-luz em um raio de 9 metros.\n\nCom uma Ação Bônus, você pode mover cada esfera até 9 metros a até 36 metros de si. Na primeira vez que a esfera chegar a 1,5 metro de uma criatura diferente de você que não esteja atrás de uma Cobertura Total, a esfera descarrega um raio naquela criatura e desaparece. Essa criatura realiza uma salvaguarda de Destreza CD 15. Se falhar, a criatura sofre dano Elétrico com base no número de esferas que você criou, conforme mostrado na tabela a seguir. Em caso de sucesso, a criatura sofre metade do dano.\n\n| Número de Esferas | Dano Elétrico |\n| :---- | :---- |\n| 1 | 4d12 |\n| 2 | 5d4 |\n| 3 | 2d6 |\n| 4 | 2d4 |\n\n***Estrelas Cadentes.*** Você pode gastar de 1 a 3 cargas como uma ação Usar Magia. Para cada carga gasta, você lança uma partícula brilhante de luz a partir do anel em um ponto à sua vista a até 18 metros de distância. Cada criatura em um Cubo de 4,5 metros de lado originado desse ponto recebe uma chuva de faíscas e realiza uma salvaguarda de Destreza CD 15, sofrendo 5d4 pontos de dano Radiante se falhar, ou metade desse dano em caso de sucesso.\n\n***Fogo das Fadas.*** Você pode gastar 1 carga para conjurar *Fogo das Fadas* a partir do anel."
  },
  {
    "nome": "Anel de Andar Sobre as Águas",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite conjurar Caminhar Sobre as Águas a partir do anel com alvo apenas em si.",
    "descricao": "Enquanto estiver usando este anel, você conjura *Caminhar Sobre as Águas* a partir dele, tendo apenas você como alvo."
  },
  {
    "nome": "Anel de Aquecimento",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Reduz dano Gélido sofrido em 2d8 e protege contra temperaturas de -18°C ou inferiores.",
    "descricao": "Se você sofrer dano Gélido enquanto estiver usando este anel, o anel reduz o dano sofrido em 2d8.\n\nAlém disso, enquanto estiver usando este anel, você e tudo o que você usa e carrega não serão prejudicados por temperaturas de -18 graus Celsius ou menos."
  },
  {
    "nome": "Anel de Aríete",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para ataques mágicos de energia à distância (2d10 por carga, +7 atq) e quebrar objetos (+5 For por carga).",
    "descricao": "Este anel tem 3 cargas e recupera 1d3 cargas gastas diariamente ao amanhecer. Enquanto estiver usando o anel, você pode executar uma ação Usar Magia para gastar de 1 a 3 cargas para fazer um ataque mágico à distância contra uma criatura à sua vista a até 18 metros de distância. O anel produz a cabeça de um carneiro espectral e realiza sua jogada de ataque com um bônus de +7. Em um acerto, para cada carga que você gasta, o alvo sofre 2d10 pontos de dano Energético e é empurrado 1,5 metro para longe de você.\n\nComo alternativa, você pode gastar de 1 a 3 das cargas do anel como uma ação Usar Magia para tentar quebrar um objeto não mágico à sua vista a até 18 metros de distância e que não esteja sendo usado ou carregado. O anel realiza um teste de Força com um bônus de +5 para cada carga gasta."
  },
  {
    "nome": "Anel de Comando Elemental",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Vinculado a um dos 4 planos elementais; concede compulsão, destruição, imunidades/resistências e magias temáticas.",
    "descricao": "Cada *Anel de Comando Elemental* está ligado a um dos quatro Planos Elementais (Ar, Terra, Fogo ou Água).\n\n**Compulsão Elemental.** Com uma ação Usar Magia, força um Elemental a até 18 m a realizar salvaguarda de Sabedoria CD 18 ou fica Encantado até o início do seu próximo turno sob suas ordens.\n\n**Destruição Elemental.** Você tem Vantagem em jogadas de ataque contra Elementais e eles têm Desvantagem em ataques contra você.\n\n***Foco Elemental:***\n- **Água:** Idioma Aquan, Natação 18 m e respiração na água.\n- **Ar:** Idioma Auran, Resistência Elétrico, Voo igual ao deslocamento e pairar.\n- **Fogo:** Idioma Ignan e Imunidade a Fogo.\n- **Terra:** Idioma Terran, Resistência a Ácido, ignora terreno difícil de pedra/terra e move-se por terra sólida/rocha.\n\n***Conjuração (5 cargas, CD 18):***\n- **Água:** Caminhar Sobre as Águas (2), Criar ou Destruir Água (1), Muralha de Gelo (3), Tempestade Glacial (2), Tsunami (5).\n- **Ar:** Corrente de Relâmpagos (3), Lufada de Vento (2), Muralha de Vento (1), Queda Suave (0).\n- **Fogo:** Bola de Fogo (2), Mãos Flamejantes (1), Muralha de Fogo (3), Tempestade de Fogo (4).\n- **Terra:** Moldar Rochas (2), Muralha de Pedra (3), Pele-Rocha (3), Terremoto (5)."
  },
  {
    "nome": "Anel de Escudo Mental",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Imunidade a leitura de pensamentos, detecção de mentiras, alinhamento e tipo de criatura; abriga a alma se morrer.",
    "descricao": "Enquanto estiver usando este anel, você é imune à magia que permite que outras criaturas leiam seus pensamentos, determinem se você está mentindo, conheçam seu alinhamento ou conheçam seu tipo de criatura. As criaturas só podem se comunicar telepaticamente com você se você permitir.\n\nVocê pode executar uma ação Usar Magia para fazer com que o anel se torne imperceptível até executar outra ação Usar Magia para torná-lo perceptível, até remover o anel ou até você morrer.\n\nSe você morrer enquanto estiver usando o anel, sua alma entra nele, a menos que ele já abrigue uma alma. Você pode permanecer no anel ou partir para a pós-vida. Enquanto sua alma estiver no anel, você pode se comunicar telepaticamente com qualquer criatura que o use. Um usuário não pode impedir essa comunicação telepática."
  },
  {
    "nome": "Anel de Evasão",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas; permite usar uma Reação para ter sucesso automático em uma salvaguarda de Destreza que falhou.",
    "descricao": "Este anel tem 3 cargas e recupera 1d3 cargas gastas diariamente ao amanhecer. Ao falhar em uma salvaguarda de Destreza enquanto estiver usando o anel, você pode executar uma Reação para gastar 1 carga para ser bem-sucedido nessa salvaguarda."
  },
  {
    "nome": "Anel de Influenciar Animais",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 3 cargas para conjurar Amizade Animal, Falar com Animais ou Medo (apenas Feras), com CD 13.",
    "descricao": "Este anel possui 3 cargas e recupera 1d3 cargas gastas diariamente ao amanhecer. Enquanto estiver usando o anel, você pode gastar 1 carga para conjurar uma das seguintes magias (CD 13 para evitar):\n\n● *Amizade Animal*\n\n● *Falar com Animais*\n\n● *Medo* (afeta apenas Feras)"
  },
  {
    "nome": "Anel de Invisibilidade",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite ficar com a condição Invisível com uma ação Usar Magia até ser removido ou cancelado por Ação Bônus.",
    "descricao": "Enquanto estiver usando este anel, você pode executar uma ação Usar Magia para adquirir a condição Invisível. Você permanece Invisível até que o anel seja removido ou até que você execute uma Ação Bônus para se tornar visível novamente."
  },
  {
    "nome": "Anel de Invocar Djinni",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Invoca um Djinni Amigável do Plano do Ar por até 1 hora (Concentração), recarregando em 24 horas.",
    "descricao": "Enquanto estiver usando este anel, você pode executar uma ação Usar Magia para invocar um determinado **Djinni** do Plano Elemental do Ar. O djinni aparece em um espaço desocupado à sua escolha a até 36 metros de você. Ele permanece enquanto você mantiver a Concentração, até um máximo de 1 hora, ou até que você tenha seus Pontos de Vida reduzidos a 0.\n\nEnquanto estiver invocado, o djinni é Amigável a você e seus aliados, obedecendo aos seus comandos. Se você não der comandos, o djinni se defende contra quem o atacar, mas não executa nenhuma outra ação.\n\nApós o djinni partir, ele não pode ser invocado novamente por 24 horas, e o anel deixa de ser mágico se o djinni morrer."
  },
  {
    "nome": "Anel de Natação",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Deslocamento de Natação de 12 metros enquanto usado.",
    "descricao": "Você tem um Deslocamento de Natação de 12 metros enquanto estiver usando este anel."
  },
  {
    "nome": "Anel de Proteção",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede um bônus de +1 na Classe de Armadura e em todas as salvaguardas.",
    "descricao": "Você recebe um bônus de +1 na Classe de Armadura e em salvaguardas enquanto estiver usando este anel."
  },
  {
    "nome": "Anel de Queda Suave",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ao cair, desce suavemente 18 metros por rodada e não sofre dano de queda.",
    "descricao": "Ao cair enquanto usa este anel, você desce 18 metros por rodada e não sofre dano devido à queda."
  },
  {
    "nome": "Anel de Regeneração",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Recupera 1d6 PV a cada 10 minutos (se tiver >=1 PV) e regenera membros perdidos em 1d6+1 dias.",
    "descricao": "Enquanto estiver usando este anel, você recupera 1d6 Pontos de Vida a cada 10 minutos se tiver pelo menos 1 Ponto de Vida. Se você perder uma parte do corpo, o anel faz com que a parte perdida volte a crescer e retorne à funcionalidade total após 1d6 + 1 dias se você tiver pelo menos 1 Ponto de Vida durante todo esse tempo."
  },
  {
    "nome": "Anel de Resistência",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Resistência a um tipo de dano determinado pela pedra preciosa encrustada.",
    "descricao": "Você tem Resistência a um tipo de dano ao usar este anel. A pedra preciosa no anel indica o tipo de dano:\n\n- Ácido (Pérola)\n- Gélido (Turmalina)\n- Ígneo (Granada)\n- Energético (Safira)\n- Elétrico (Citrino)\n- Necrótico (Azeviche)\n- Venenoso (Ametista)\n- Psíquico (Jade)\n- Radiante (Topázio)\n- Trovejante (Espinela)"
  },
  {
    "nome": "Anel de Saltar",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar Salto a partir do anel com alvo apenas em si.",
    "descricao": "Enquanto estiver usando este anel, você pode conjurar *Salto* a partir dele, mas só pode escolher a si mesmo como alvo quando o fizer."
  },
  {
    "nome": "Anel de Telecinese",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar Telecinese a partir dele.",
    "descricao": "Enquanto estiver usando este anel, você pode conjurar *Telecinese* a partir dele."
  },
  {
    "nome": "Anel de Visão de Raio-X",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede visão de raio-X até 9 metros por 1 minuto (usos repetidos exigem salvaguarda CD 15 Con contra Exaustão).",
    "descricao": "Enquanto estiver usando este anel, você pode executar uma ação Usar Magia para adquirir visão de raio-X com alcance de 9 metros por 1 minuto. Para você, objetos sólidos dentro desse raio aparecem transparentes e não impedem que a luz passe por eles. A visão pode penetrar 30 centímetros de pedra, 2,5 centímetros de metal comum ou até 90 centímetros de madeira ou terra. Substâncias mais espessas ou uma fina camada de chumbo bloqueiam a visão.\n\nSempre que usar o anel novamente antes de fazer um Descanso Longo, você deve ser bem-sucedido em uma salvaguarda de Constituição CD 15 ou adquire 1 nível de Exaustão."
  },
  {
    "nome": "Anel dos Três Desejos",
    "tipo": "Anel",
    "subtipo": "",
    "tipo_linha": "Anel, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 3 cargas para conjurar Desejo; torna-se não mágico após a última carga.",
    "descricao": "Enquanto estiver usando este anel, você pode gastar 1 de suas 3 cargas para conjurar *Desejo* a partir dele. O anel se torna não mágico quando você usa a última carga."
  },
  {
    "nome": "Arco de Energia",
    "tipo": "Arma",
    "subtipo": "Arco Curto ou Arco Longo",
    "tipo_linha": "Arma (Arco Curto ou Arco Longo), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Arco +1 sem corda que dispara flechas de energia luminosa; possui Flecha de Contenção, Flecha de Transporte e Escada de Energia.",
    "descricao": "Você adquire um bônus de +1 nas jogadas de ataque e dano realizadas com esta arma mágica, que não possui corda. Sempre que você faz o movimento de disparar puxando o braço para trás, uma flecha mágica feita de energia dourada aparece encaixada e pronta para ser disparada. Uma flecha criada por esta arma causa dano Energético em vez de dano Perfurante ao acertar, e desaparece após acertar ou errar o alvo. Até desaparecer, a flecha emite Luz Plena em um raio de 6 metros e Meia-luz por mais 6 metros.\n\n***Flecha de Contenção.*** Em vez de dano, o alvo deve passar em salvaguarda de Força CD 15 ou fica Contido por 1 minuto (ação Atletismo CD 20 para escapar).\n\n***Flecha de Transporte.*** Com uma ação Usar Magia, teleporta criatura voluntária Média ou menor (ou objeto até cubo de 1,5 m) a até 18 m para até 3 m de você.\n\n***Escada de Energia.*** Com uma ação Usar Magia, dispara flechas em uma parede criando uma escada mágica de até 18 metros por 1 minuto."
  },
  {
    "nome": "Arco do Juramento",
    "tipo": "Arma",
    "subtipo": "Arco Curto ou Arco Longo",
    "tipo_linha": "Arma (Arco Curto ou Arco Longo), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite jurar um inimigo: concede Vantagem no ataque, ignora coberturas parciais/distância máxima e causa +3d6 perfurante.",
    "descricao": "Ao colocar uma flecha neste arco, ele sussurra em Élfico: “Célere derrota aos meus inimigos”. Ao usar esta arma para um ataque à distância, você pode proferir as palavras de comando: “Morte rápida àquele que me feriu”. O alvo do seu ataque se torna seu inimigo jurado até morrer ou até o amanhecer 7 dias depois. Você pode ter apenas um inimigo jurado por vez.\n\nAo realizar ataque à distância contra o inimigo jurado, você tem Vantagem, ignora Cobertura Parcial e Três Quartos, e não sofre Desvantagem por alcance máximo. Em caso de acerto, causa 3d6 pontos de dano Perfurante adicionais.\n\nEnquanto seu inimigo jurado viver, você tem Desvantagem em jogadas de ataque com todas as outras armas."
  },
  {
    "nome": "Arma de Adamantina",
    "tipo": "Arma",
    "subtipo": "Qualquer Munição ou Arma Corpo a Corpo",
    "tipo_linha": "Arma (Qualquer Munição ou Arma Corpo a Corpo), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Feita de adamantina; causa um Acerto Crítico automático ao atingir um objeto.",
    "descricao": "Esta arma ou munição, feita de adamantina, uma das substâncias mais duras existentes, causa um Acerto Crítico ao atingir um objeto."
  },
  {
    "nome": "Arma de Prata",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Unida alquimicamente a prata; causa um dado adicional de dano em acerto crítico contra criaturas multimorfadas.",
    "descricao": "Um processo alquímico uniu prata a esta arma mágica. Ao obter um Acerto Crítico com ela contra uma criatura que está multimorfada, a arma causa um dado adicional de dano."
  },
  {
    "nome": "Arma Implacável",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Arma mágica que causa 2d6 pontos de dano adicionais do mesmo tipo da arma em qualquer acerto.",
    "descricao": "Esta arma mágica causa 2d6 pontos de dano adicionais a qualquer criatura atingida. Este dano adicional é do mesmo tipo do dano normal da arma."
  },
  {
    "nome": "Arma Magificada",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Raridade Varia (Requer Sintonização)",
    "raridade": "Raridade Variável",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Contém uma magia vinculada de 8º círculo ou menor (6 cargas, 1d6 recarga diária).",
    "descricao": "Esta arma contém uma magia de 8º círculo ou inferior vinculada a ela (Adivinhação, Evocação, Invocação, Necromancia ou Transmutação). A arma possui 6 cargas e recupera 1d6 cargas gastas diariamente ao amanhecer. Enquanto estiver segurando a arma, você pode gastar 1 carga para conjurar a magia vinculada a ela.\n\n| Círculo de Magia | Raridade | CD da Salvaguarda | Bônus de Ataque |\n| :---- | :---- | :---- | :---- |\n| Truque | Incomum | 13 | +5 |\n| 1 | Incomum | 13 | +5 |\n| 2 | Raro | 13 | +5 |\n| 3 | Raro | 15 | +7 |\n| 4 | Muito Raro | 15 | +7 |\n| 5 | Muito Raro | 17 | +9 |\n| 6 | Lendário | 17 | +9 |\n| 7 | Lendário | 18 | +10 |\n| 8 | Lendário | 18 | +10 |"
  },
  {
    "nome": "Arma Sempre Alerta",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Desperta você e aliados a até 9 m no início do combate e concede Vantagem em jogadas de Iniciativa.",
    "descricao": "Contanto que esta arma esteja ao seu alcance e você esteja sintonizado com ela, você e seus aliados a até 9 metros de distância adquirem os seguintes benefícios:\n\n***Alarme.*** A arma desperta magicamente cada sujeito que está dormindo naturalmente quando um combate se inicia.\n\n***Prontidão Sobrenatural.*** Cada sujeito tem Vantagem em jogadas de Iniciativa."
  },
  {
    "nome": "Arma, +1, +2 ou +3",
    "tipo": "Arma",
    "subtipo": "Qualquer Simples ou Marcial",
    "tipo_linha": "Arma (Qualquer Simples ou Marcial), Incomum (+1), Raro (+2) ou Muito Raro (+3)",
    "raridade": "Incomum (+1), Raro (+2), Muito Raro (+3)",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede um bônus de +1, +2 ou +3 nas jogadas de ataque e dano realizadas com ela.",
    "descricao": "Você adquire um bônus em jogadas de ataque e dano realizadas com esta arma mágica. O bônus é determinado pela raridade da arma (+1 Incomum, +2 Raro, +3 Muito Raro)."
  },
  {
    "nome": "Armadura Adamantina",
    "tipo": "Armadura",
    "subtipo": "Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Média ou Pesada, Exceto Gibão de Peles), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Reforçada com adamantina; qualquer Acerto Crítico sofrido pelo portador se torna um acerto normal.",
    "descricao": "Esta armadura é reforçada com adamantina, uma das substâncias mais duras existentes. Enquanto estiver usando, qualquer Acerto Crítico contra você se torna um acerto normal."
  },
  {
    "nome": "Armadura de Invulnerabilidade",
    "tipo": "Armadura",
    "subtipo": "Armadura de Placas",
    "tipo_linha": "Armadura (Armadura de Placas), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Resistência a dano Contundente, Cortante e Perfurante; pode ativar Imunidade total a esses danos por 10 min 1x/dia.",
    "descricao": "Você tem Resistência a dano Contundente, Cortante e Perfurante enquanto usa esta armadura.\n\n***Carapaça Metálica.*** Você pode executar uma ação Usar Magia para obter Imunidade a dano Contundente, Cortante e Perfurante por 10 minutos ou até não usar mais a armadura. Você restaura o uso desta propriedade após o amanhecer."
  },
  {
    "nome": "Armadura de Mitral",
    "tipo": "Armadura",
    "subtipo": "Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Média ou Pesada, Exceto Gibão de Peles), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Feita de mitral leve e flexível; pode ser vestida sob roupas e não impõe Desvantagem em Furtividade nem exigência de Força.",
    "descricao": "O mitral é um metal leve e flexível. Armaduras feitas dessa substância podem ser usadas sob roupas normais. Caso a armadura imponha Desvantagem em testes de Destreza (Furtividade) ou possua exigência de Força, a versão em mitral ignora essas limitações."
  },
  {
    "nome": "Armadura de Placas das Formas Etéreas",
    "tipo": "Armadura",
    "subtipo": "Armadura de Placas Parcial ou Placas",
    "tipo_linha": "Armadura (Armadura de Placas Parcial ou Armadura de Placas), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar o efeito da magia Forma Etérea com palavra de comando 1x ao dia.",
    "descricao": "Enquanto estiver vestindo esta armadura, você pode executar uma ação Usar Magia e usar uma palavra de comando para obter o efeito da magia *Forma Etérea*. A magia encerra imediatamente se você remover a armadura ou executar uma ação Usar Magia para repetir a palavra de comando. Esta propriedade da armadura não pode ser usada novamente até o próximo amanhecer."
  },
  {
    "nome": "Armadura de Placas do Povo Anão",
    "tipo": "Armadura",
    "subtipo": "Armadura de Placas ou Placas Parcial",
    "tipo_linha": "Armadura (Armadura de Placas ou Placas Parcial), Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede +2 na CA e permite usar uma Reação para reduzir deslocamentos involuntários pelo chão em até 3 metros.",
    "descricao": "Enquanto estiver vestindo esta armadura, você adquire um bônus de +2 na Classe de Armadura. Além disso, se um efeito mover você contra sua vontade pelo chão, você pode executar uma Reação para reduzir a distância em até 3 metros."
  },
  {
    "nome": "Armadura de Resistência",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede Resistência a um tipo de dano elemental ou energético enquanto usada.",
    "descricao": "Você tem Resistência a um tipo de dano enquanto usa esta armadura (Ácido, Gélido, Ígneo, Energético, Elétrico, Necrótico, Venenoso, Psíquico, Radiante ou Trovejante)."
  },
  {
    "nome": "Armadura de Vulnerabilidade",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede Resistência a um tipo de dano físico, mas é amaldiçoada com Vulnerabilidade aos outros dois tipos físicos.",
    "descricao": "Enquanto estiver usando esta armadura, você tem Resistência a um dos seguintes tipos de dano: Contundente, Cortante ou Perfurante.\n\n***Maldição.*** Esta armadura é amaldiçoada. Enquanto amaldiçoado, você tem Vulnerabilidade aos outros dois tipos de dano físico não concedidos pela armadura."
  },
  {
    "nome": "Armadura Demoníaca",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede +1 CA, idioma Abissal e garras de 1d8 cortante (+1 ataque/dano); amaldiçoada contra demônios.",
    "descricao": "Enquanto estiver vestindo esta armadura, você adquire um bônus de +1 na Classe de Armadura e conhece o idioma Abissal. Além disso, as manoplas com garras da armadura permitem que seus Ataques Desarmados causem 1d8 pontos de dano Cortante e você tem +1 em jogadas de ataque e dano com eles.\n\n***Maldição.*** Você tem Desvantagem em ataques contra demônios e em salvaguardas contra magias e habilidades deles."
  },
  {
    "nome": "Armadura do Marinheiro",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Deslocamento de Natação igual ao deslocamento e cura 1d4 PV ao iniciar turno debaixo d'água com 0 PV.",
    "descricao": "Enquanto estiver vestindo esta armadura, você tem um Deslocamento de Natação igual ao seu Deslocamento. Além disso, se começar seu turno debaixo d'água com 0 Pontos de Vida, você recupera imediatamente 1d4 Pontos de Vida (1x ao dia)."
  },
  {
    "nome": "Armadura Fácil de Tirar",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pode ser despida instantaneamente como uma ação Usar Magia.",
    "descricao": "Você pode despir esta armadura como uma ação Usar Magia."
  },
  {
    "nome": "Armadura Fumegante",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Pesada, Média ou Leve), Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Fumos tênues, inofensivos e inodoros se elevam da armadura enquanto vestida.",
    "descricao": "Fumos tênues, inofensivos e sem odor se elevam desta armadura enquanto ela está sendo vestida."
  },
  {
    "nome": "Armadura Magificada",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Raridade Variável (Requer Sintonização)",
    "raridade": "Raridade Variável",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Contém magia de Abjuração ou Ilusão de 8º círculo ou menor vinculada a ela (6 cargas, 1d6 recarga diária).",
    "descricao": "Esta armadura contém uma magia de 8º círculo ou inferior vinculada a ela (Abjuração ou Ilusão). Possui 6 cargas e recupera 1d6 cargas ao amanhecer.\n\n| Círculo de Magia | Raridade | CD da Salvaguarda | Bônus de Ataque |\n| :---- | :---- | :---- | :---- |\n| Truque | Incomum | 13 | +5 |\n| 1 | Incomum | 13 | +5 |\n| 2 | Raro | 13 | +5 |\n| 3 | Raro | 15 | +7 |\n| 4 | Muito Raro | 15 | +7 |\n| 5 | Muito Raro | 17 | +9 |\n| 6 | Lendário | 17 | +9 |\n| 7 | Lendário | 18 | +10 |\n| 8 | Lendário | 18 | +10 |"
  },
  {
    "nome": "Armadura Reluzente",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Esta armadura mágica nunca fica suja.",
    "descricao": "Esta armadura nunca fica suja."
  },
  {
    "nome": "Armadura, +1, +2 ou +3",
    "tipo": "Armadura",
    "subtipo": "Leve, Média ou Pesada",
    "tipo_linha": "Armadura (Qualquer Leve, Média ou Pesada), Raro (+1), Muito Raro (+2) ou Lendário (+3)",
    "raridade": "Raro (+1), Muito Raro (+2), Lendário (+3)",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede um bônus de +1, +2 ou +3 na Classe de Armadura.",
    "descricao": "Você tem um bônus na Classe de Armadura enquanto estiver usando esta armadura. O bônus é determinado pela raridade da armadura (+1 Raro, +2 Muito Raro, +3 Lendário)."
  },
  {
    "nome": "Ataduras do Poder Desarmado",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (+1), Raro (+2) ou Muito Raro (+3)",
    "raridade": "Incomum (+1), Raro (+2), Muito Raro (+3)",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede bônus de +1 a +3 em ataque e dano desarmados, e permite causar dano Energético opcional.",
    "descricao": "Enquanto estiver vestindo estas ataduras, você tem um bônus em jogadas de ataque e dano realizadas com seus Ataques Desarmados. O bônus é determinado pela raridade das ataduras (+1, +2 ou +3), e esses golpes causam, à sua escolha, dano Energético ou o tipo de dano normal."
  },
  {
    "nome": "Azagaia Relâmpago",
    "tipo": "Arma",
    "subtipo": "Azagaia",
    "tipo_linha": "Arma (Azagaia), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pode causar dano Elétrico e transforma-se em relâmpago de 36 m causando 4d6 elétrico (CD 13 Des) 1x ao dia.",
    "descricao": "Toda vez que realizar uma jogada de ataque com esta arma mágica e acertar, você pode causar dano Elétrico em vez de dano Perfurante.\n\n***Relâmpago.*** Ao arremessar esta arma em um alvo a até 36 metros, você pode transformá-la em um relâmpago em linha de 1,5 m de largura. Cada criatura na linha realiza salvaguarda de Destreza CD 13, sofrendo 4d6 de dano Elétrico (metade se passar). Após o dano, a arma reaparece na sua mão (1x ao dia)."
  },
  {
    "nome": "Baralho das Ilusões",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Conjunto de cartas mágicas que projetam ilusões de criaturas ao serem tiradas e jogadas no chão.",
    "descricao": "Esta caixa contém cartas que criam ilusões de criaturas (Dragão Vermelho, Observador, Lich, etc.) quando puxadas aleatoriamente e jogadas ao chão a até 9 metros. A ilusão pode ser movida enquanto estiver a até 36 m. Investigação CD 15 para discernir a ilusão."
  },
  {
    "nome": "Baralho de Muitas Coisas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Lendário baralho de 13 ou 22 cartas com efeitos cósmicos drásticos (Desejos, Avatar da Morte, atributos, ruína, etc.).",
    "descricao": "Contém cartas feitas de marfim ou velino com efeitos transcendentais ao serem declaradas e puxadas:\n- **Bufão:** Vantagem em D20 por 72h ou 2 cartas extras.\n- **Cavaleiro:** Serviço leal de um Cavaleiro.\n- **Chave:** Arma mágica rara ou superior.\n- **Crânio:** Invoca Avatar da Morte para enfrentá-lo.\n- **Estrela:** +2 em um atributo (máx 24).\n- **Lua:** 1d3 conjurações de Desejo.\n- **Sol:** Item mágico + 10 PV temporários diários.\n- **Tolo, Ruína, Vazio, Labaredas, Ladino, Parcas, Calabouço, Equilíbrio, Enigma, etc.**"
  },
  {
    "nome": "Barco de Bolso",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Caixa de madeira de 2 kg que se desdobra magicamente em Barco a Remo ou Barco de Quilha por palavra de comando.",
    "descricao": "Caixa de madeira de 30x15x15 cm pesando 2 kg. Possui 3 palavras de comando:\n1. Desdobra-se em um Barco a Remo.\n2. Desdobra-se em um Barco de Quilha.\n3. Dobra-se de volta em caixa (se desocupado)."
  },
  {
    "nome": "Batuta da Regência",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 3 cargas para criar música orquestral audível a até 36 metros enquanto agitada.",
    "descricao": "Esta varinha tem 3 cargas. Enquanto a segura, você pode gastar 1 carga para criar música orquestral audível a até 36 metros agitando-a."
  },
  {
    "nome": "Bengala de Veterano",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pode ser transformada em Espada Longa comum ou de volta em bengala como uma Ação Bônus.",
    "descricao": "Como uma Ação Bônus, você pode transformar esta bengala em uma Espada Longa comum ou transformar a Espada Longa de volta em uma bengala."
  },
  {
    "nome": "Bola de Cristal",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar Vidência (CD 17 para evitar) ao tocar o orbe de cristal.",
    "descricao": "Ao tocar neste orbe de cristal, você pode conjurar *Vidência* (CD 17 para evitar) com ele."
  },
  {
    "nome": "Bola de Cristal da Leitura de Mentes",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar Vidência e Detectar Pensamentos (CD 17) em alvos a até 9 m do sensor.",
    "descricao": "Ao tocar neste orbe de cristal, você pode conjurar *Vidência* (CD 17). Além disso, pode conjurar *Detectar Pensamentos* (CD 17) em criaturas a até 9 m do sensor sem requerer concentração adicional."
  },
  {
    "nome": "Bola de Cristal de Telepatia",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite Vidência, telepatia a até 9 m do sensor e conjurar Sugestão (CD 17) 1x ao dia através dele.",
    "descricao": "Ao tocar neste orbe de cristal, conjura *Vidência* (CD 17). Permite comunicação telepática com criaturas a até 9 m do sensor e conjurar *Sugestão* (CD 17) 1x ao dia através do sensor."
  },
  {
    "nome": "Bola de Cristal de Visão Verdadeira",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite Vidência (CD 17) e confere Visão Verdadeira a até 36 metros centrado no sensor.",
    "descricao": "Ao tocar neste orbe de cristal, você pode conjurar *Vidência* (CD 17). Além disso, você tem Visão Verdadeira com alcance de 36 metros centrado no sensor mágico."
  },
  {
    "nome": "Bolsa Cabe Tudo",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Bolsa extradimensional que armazena até 250 kg e 1,8 m³ de volume pesando sempre 7,5 kg.",
    "descricao": "Esta bolsa tem espaço interno de 60 cm de diâmetro e 1,2 m de profundidade, comportando até 250 kg (1,8 m³). Pesa sempre 7,5 kg. Retirar item requer ação Usar Objeto. Destruída se perfurada/sobrecarregada; colocar dentro de outro espaço extradimensional abre portal para o Plano Astral."
  },
  {
    "nome": "Bolsa das Tropelias",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite puxar até 3 objetos por dia que se transformam em feras aliadas ao serem arremessados.",
    "descricao": "Com uma ação Usar Magia, puxe um objeto e arremesse até 6 metros para transformá-lo em uma criatura aliada (conforme a cor: Bronze, Cinza ou Ferrugem). Age logo após seu turno. Até 3 criaturas por dia."
  },
  {
    "nome": "Bolsa de Feijões",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Contém feijões mágicos que geram efeitos bizarros e surpreendentes quando plantados e regados.",
    "descricao": "Contém 3d4 feijões secos. Despejar todos no chão causa explosão de 5d4 dano energético (CD 15 Des). Plantar e regar 1 feijão gera efeitos mágicos aleatórios (cogumelos mutagênicos, gêiseres, Ents, árvores frutíferas com poções, pirâmide com múmias ou pé de feijão gigante)."
  },
  {
    "nome": "Bolsa de Temperos Prestativa de Howard",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 10 cargas para produzir uma pitada de qualquer tempero alimentício não mágico.",
    "descricao": "Com uma ação Usar Magia, gaste 1 carga para falar o nome de qualquer tempero não mágico e retirar uma pitada suficiente para temperar uma refeição (recupera 1d6+4 cargas ao amanhecer)."
  },
  {
    "nome": "Bolsa Devoradora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Assemelha-se a uma Bolsa Cabe Tudo, mas é o orifício alimentar de uma criatura extradimensional devoradora.",
    "descricao": "Devora matéria animal e vegetal inserida nela. Se uma criatura colocar parte do corpo dentro, há 50% de chance de ser puxada (Atletismo CD 15 para escapar). Criaturas que começam o turno dentro são devoradas e destruídas."
  },
  {
    "nome": "Boneca Conversadora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite programar até seis frases com condições de ativação quando alguém estiver próximo.",
    "descricao": "Durante um Descanso Curto, você pode programar até seis frases (de até 6 palavras) com condições que ativam a fala da boneca quando ocorrem a até 1,5 m dela."
  },
  {
    "nome": "Botas Aladas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possuem 4 cargas para conceder Deslocamento de Voo de 9 metros por 1 hora cada.",
    "descricao": "Estas botas têm 4 cargas (1d4 recuperadas ao amanhecer). Com uma ação Usar Magia, gasta 1 carga para receber Deslocamento de Voo de 9 metros por 1 hora."
  },
  {
    "nome": "Botas das Terras Glaciais",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ignora terreno difícil de gelo/neve, confere Resistência a dano Gélido e proteção contra frio extremo (-18°C).",
    "descricao": "Ignora Terreno Difícil gerado por gelo ou neve, concede Resistência a dano Gélido e tolerância a temperaturas de -18°C ou menos."
  },
  {
    "nome": "Botas de Caminhar e Saltar",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Deslocamento mínimo de 9 m (sem redução por carga ou armadura pesada); permite saltar 9 m gastando 3 m.",
    "descricao": "Seu deslocamento torna-se no mínimo 9 metros e não é reduzido por carga pesada ou armadura pesada. Uma vez por turno, salta até 9 metros gastando apenas 3 metros de movimento."
  },
  {
    "nome": "Botas de Levitação",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permitem conjurar Levitação em si mesmo à vontade.",
    "descricao": "Enquanto estiver usando estas botas, você pode conjurar *Levitação* em si mesmo."
  },
  {
    "nome": "Botas de Velocidade",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ação Bônus para dobrar Deslocamento e impor Desvantagem em ataques de oportunidade contra você por até 10 min.",
    "descricao": "Com uma Ação Bônus ao bater os calcanhares, dobra seu Deslocamento e impõe Desvantagem em Ataques de Oportunidade contra você por até 10 minutos (recarrega em Descanso Longo)."
  },
  {
    "nome": "Botas Despistadoras",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite deixar pegadas como as de qualquer tipo de humanoide do mesmo tamanho.",
    "descricao": "Enquanto estiver usando essas botas, você pode fazer com que elas deixem pegadas como as de qualquer tipo de humanoide do seu tamanho."
  },
  {
    "nome": "Botas Élficas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Passos completamente silenciosos e Vantagem em testes de Destreza (Furtividade).",
    "descricao": "Seus passos não fazem barulho, independentemente da superfície. Você também tem Vantagem em testes de Destreza (Furtividade)."
  },
  {
    "nome": "Braceletes de Arquearia",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Proficiência com Arco Curto e Longo, além de bônus de +2 nas jogadas de dano com essas armas.",
    "descricao": "Enquanto estiver usando estes braceletes, você tem proficiência com o Arco Longo e o Arco Curto, e recebe um bônus de +2 nas jogadas de dano realizadas com essas armas."
  },
  {
    "nome": "Braceletes de Defesa",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede um bônus de +2 na Classe de Armadura se não estiver vestindo armadura nem usando escudo.",
    "descricao": "Enquanto estiver usando estes braceletes, você recebe um bônus de +2 na Classe de Armadura se não estiver vestindo armadura e não estiver usando Escudo."
  },
  {
    "nome": "Braseiro de Comandar Elementais do Fogo",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite invocar um Elemental do Fogo obediente por até 1 hora 1x ao dia.",
    "descricao": "Com uma ação Usar Magia a até 1,5 m, invoca um **Elemental do Fogo** que entende seus idiomas e obedece aos seus comandos por até 1 hora (1x ao dia)."
  },
  {
    "nome": "Broche Escudarcano",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede Resistência a dano Energético e Imunidade ao dano da magia Míssil Mágico.",
    "descricao": "Enquanto estiver usando este broche, você tem Resistência a dano Energético e Imunidade ao dano da magia *Míssil Mágico*."
  },
  {
    "nome": "Buraco Portátil",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Tecido circular de 1,8 m que se abre em um buraco extradimensional de 3 m de profundidade ao ser fixado em uma superfície.",
    "descricao": "Pode ser desdobrado sobre uma superfície para abrir um buraco extradimensional de 1,8 m de diâmetro e 3 m de profundidade. Dobrar o tecido fecha o buraco mantendo o conteúdo dentro. Pesa quase nada. Contém ar para 1 hora."
  }
];
