module.exports = [
  {
    "nome": "Roupas Autoconcertantes",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Consertam e remendam automaticamente rasgos, furos e desgastes instantaneamente.",
    "descricao": "Estas roupas se remendam e reparam magicamente de rasgos, furos e queimaduras de forma instantânea e contínua."
  },
  {
    "nome": "Rubi do Mago de Batalha",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização por um Conjurador)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Fixa-se a uma arma simples ou marcial, permitindo usá-la como Foco de Conjuração para suas magias.",
    "descricao": "Fixado à lâmina ou cabo de uma arma simples ou marcial, permite que você utilize aquela arma como Foco de Conjuração para todas as suas magias."
  },
  {
    "nome": "Sacro Vingadora",
    "tipo": "Arma",
    "subtipo": "Qualquer Espada",
    "tipo_linha": "Arma (Qualquer Espada), Lendário (Requer Sintonização por um Paladino)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Paladino",
    "resumo": "Espada lendária +3 (+2d10 dano radiante extra contra Ínferos e Mortos-Vivos); concede Aura Sagrada de 3 m (ou 9 m em nível 17) de Vantagem em salvaguardas contra magias para você e aliados.",
    "descricao": "Você adquire um bônus de +3 em jogadas de ataque e dano realizadas com esta arma mágica. Ao atingir um Ínfero ou Morto-Vivo, causa 2d10 pontos de dano Radiante adicionais.\n\n***Aura de Vingança Sagrada.*** Enquanto desembainhada, você e aliados a até 3 metros de você (ou 9 metros se você tiver 17 ou mais níveis de Paladino) têm Vantagem em salvaguardas contra magias e outros efeitos mágicos."
  },
  {
    "nome": "Sandálias de Escalada de Aranha",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concedem Deslocamento de Escalada igual ao seu Deslocamento, permitindo andar em paredes e tetos com as mãos livres.",
    "descricao": "Enquanto estiver calçando estas sandálias leves, você pode se mover para cima, para baixo e através de superfícies verticais ou ao longo de tetos, mantendo as mãos livres. Seu Deslocamento de Escalada é igual ao seu Deslocamento no chão."
  },
  {
    "nome": "Sela do Cavaleiro",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Impede você de ser derrubado da sela contra a sua vontade e impõe Desvantagem em ataques direcionados à sua montaria.",
    "descricao": "Enquanto estiver nesta sela, você não pode ser derrubado de sua montaria contra a sua vontade se estiver consciente. Além disso, jogadas de ataque contra sua montaria têm Desvantagem."
  },
  {
    "nome": "Solvente Universal",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Líquido que dissolve e anula instantaneamente qualquer adesivo mágico, incluindo a Cola Suprema.",
    "descricao": "Este tubo contém um líquido leitoso que dissolve e quebra imediatamente a ligação de qualquer adesivo mágico, incluindo a *Cola Suprema*."
  },
  {
    "nome": "Sorvedora das Nove Almas",
    "tipo": "Arma",
    "subtipo": "Qualquer Espada",
    "tipo_linha": "Arma (Qualquer Espada), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Espada +2 que drena a alma de criaturas vivas com <=100 PV no acerto crítico (CD 15 Con), aprisionando até 9 almas.",
    "descricao": "Concede +2 em jogadas de ataque e dano. Ao obter um Acerto Crítico contra criatura viva com 100 PV ou menos, ela deve ser bem-sucedida em salvaguarda de Constituição CD 15 ou morre instantaneamente e sua alma é sugada para a espada (armazena até 9 almas)."
  },
  {
    "nome": "Tabuleiro Espiritual",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Prancha com letras e ponteiro que permite realizar sessões espíritas para conjurar Falar com os Mortos 1x ao dia.",
    "descricao": "Com uma sessão de 10 minutos reunindo até 4 participantes em torno deste tabuleiro de madeira com ponteiro, permite conjurar a magia *Falar com os Mortos* 1x ao dia."
  },
  {
    "nome": "Tacape Trovejante",
    "tipo": "Arma",
    "subtipo": "Clava ou Bastão",
    "tipo_linha": "Arma (Clava ou Bastão), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Arma +2 que causa +2d8 dano Trovejante ao acertar e empurra o alvo 3 m para trás.",
    "descricao": "Concede +2 em jogadas de ataque e dano. Em cada acerto, causa 2d8 pontos de dano Trovejante adicionais e empurra a criatura 3 metros para trás."
  },
  {
    "nome": "Talismã da Esfera",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Dobra o bônus de proficiência em testes de Arcanismo para controlar uma Esfera da Aniquilação e permite movê-la 2x mais rápido.",
    "descricao": "Enquanto usar este talismã, você adiciona o dobro do seu Bônus de Proficiência em testes de Arcanismo para controlar uma *Esfera da Aniquilação*, e pode movê-la até 18 metros em vez de 9 m."
  },
  {
    "nome": "Talismã do Bem Sem Ver a Quem",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização por uma Criatura Boa)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Criatura de Tendência Boa",
    "resumo": "Talismã sagrado com 6 cargas: fendas divinas que engolem criaturas malignas (CD 20 Des) banindo-as instantaneamente para as profundezas.",
    "descricao": "Possui 6 cargas. Com uma ação Usar Magia, abre uma fenda sob uma criatura maligna a até 36 m: ela realiza salvaguarda de Destreza CD 20, sendo engolida e destruída em caso de falha. Se uma criatura de tendência Má tocar no talismã, sofre 6d6 de dano Radiante."
  },
  {
    "nome": "Talismã do Mal Universal",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização por uma Criatura Maligna)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Criatura de Tendência Má",
    "resumo": "Talismã profano com 6 cargas: fendas ardentes que engolem e aniquilam criaturas boas (CD 20 Des).",
    "descricao": "Possui 6 cargas. Com ação Usar Magia, abre fenda flamejante sob criatura boa a até 36 m: salvaguarda de Destreza CD 20 ou é tragada e aniquilada para sempre. Criaturas boas que tocarem nele sofrem 6d6 de dano Radiante."
  },
  {
    "nome": "Tapete Voador",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Tapete voador com comando de voz que voa até 24 m/turno (ou 18 m com carga pesada até 400 kg).",
    "descricao": "Pode transportar até 400 kg voando pelo ar por palavras de comando a até 9 metros. Possui Deslocamento de Voo de 24 metros (reduzido para 18 m ou 12 m conforme a capacidade total de peso ocupada)."
  },
  {
    "nome": "Tiara do Intelecto",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Seu valor de Inteligência torna-se 19 enquanto usar esta tiara (sem efeito se já for 19 ou superior).",
    "descricao": "Sua Inteligência é fixada em 19 enquanto você estiver usando esta tiara de prata com pedras cintilantes; se sua Inteligência já for 19 ou superior, ela não tem efeito."
  },
  {
    "nome": "Tigela de Comandar Elementais da Água",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ao enchê-la de água fresca ou salgada, invoca um Elemental da Água obediente por até 1 hora 1x ao dia.",
    "descricao": "Ao preenchê-la com água como ação Usar Magia, conjura e invoca um **Elemental da Água** obediente por até 1 hora (1x ao dia)."
  },
  {
    "nome": "Tomo da Compreensão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estudo por 48 horas aumenta o valor e o limite máximo de Sabedoria em +2 permanentemente.",
    "descricao": "Após 48 horas gastas lendo e meditando neste livro ao longo de 6 dias ou menos, seu valor de Sabedoria aumenta em 2 e seu valor máximo para esse atributo passa a ser 22. O livro perde sua magia por 1 século."
  },
  {
    "nome": "Tomo da Liderança e Influência",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estudo por 48 horas aumenta o valor e o limite máximo de Carisma em +2 permanentemente.",
    "descricao": "Após 48 horas gastas lendo este tomo sobre retórica e liderança ao longo de 6 dias ou menos, seu valor de Carisma aumenta em 2 e seu valor máximo para esse atributo passa a ser 22. O tomo perde sua magia por 1 século."
  },
  {
    "nome": "Tomo das Palavras Tranquilizantes",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Livro de poesia mágica que encerra a condição Amedrontado ao ser lido durante um Descanso Curto.",
    "descricao": "Ler este livro de poesias relaxantes durante um Descanso Curto encerra a condição Amedrontado em você e em até 4 aliados que o escutarem."
  },
  {
    "nome": "Tomo dos Pensamentos Objetivos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estudo por 48 horas aumenta o valor e o limite máximo de Inteligência em +2 permanentemente.",
    "descricao": "Após 48 horas gastas estudando este livro de lógica pura ao longo de 6 dias ou menos, seu valor de Inteligência aumenta em 2 e seu valor máximo para esse atributo passa a ser 22. O livro perde sua magia por 1 século."
  },
  {
    "nome": "Touca de Respirar na Água",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Cria uma bolha de ar límpido ao redor da cabeça enquanto submerso, permitindo respirar normalmente debaixo d'água.",
    "descricao": "Enquanto estiver usando este gorro com conchas, uma bolha de ar mágico límpido envolve sua cabeça enquanto você estiver debaixo d'água, permitindo respirar normalmente."
  },
  {
    "nome": "Tridente de Comandar Peixes",
    "tipo": "Arma",
    "subtipo": "Tridente",
    "tipo_linha": "Arma (Tridente), Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para conjurar Dominar Fera (CD 15) em qualquer criatura que possua Deslocamento de Natação.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga para conjurar *Dominar Fera* (CD 15) tendo como alvo qualquer criatura com Deslocamento de Natação nativo."
  },
  {
    "nome": "Trombeta de Explosão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Soprar emite cone sônico de 9 m causando 5d6 dano Trovejante, Surdo e atordoando objetos (20% de chance cumulativa de explodir em usos repetidos).",
    "descricao": "Ao soprar com ação Usar Objeto, emite cone de 9 metros causando 5d6 pontos de dano Trovejante e Surdez (CD 15 Con). Se usada mais de uma vez ao dia, possui 20% cumulativo de chance de explodir causando 10d6 de dano a quem soprou."
  },
  {
    "nome": "Trombeta do Valhalla",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raridade Variável",
    "raridade": "Raridade Variável",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Soprar a trombeta convoca guerreiros berserkers espirituais heroicos de Ysgard para lutar ao seu lado por 1 hora (1x a cada 7 dias).",
    "descricao": "Soprar esta trombeta prateada convoca guerreiros berserkers espirituais leais de Ysgard que obedecem a seus comandos por até 1 hora (1x a cada 7 dias):\n- **Prata (Raro):** 2d4 + 2 guerreiros\n- **Latão (Raro):** 3d4 + 3 guerreiros\n- **Bronze (Muito Raro):** 4d4 + 4 guerreiros\n- **Ferro (Lendário):** 5d4 + 5 guerreiros"
  },
  {
    "nome": "Túnica das Cores Cintilantes",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para emitir padrões cromáticos hipnóticos que impõem Desvantagem em ataques contra você e atordoam criaturas que olharem (CD 15 Sab).",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga para emitir padrões cromáticos deslumbrantes por 1 minuto: ataques contra você têm Desvantagem e criaturas em 9 m que olharem devem passar em salvaguarda de Sabedoria CD 15 ou ficam Atordoadas por 1 rodada."
  },
  {
    "nome": "Túnica das Estrelas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede +1 em todas as salvaguardas, 6 estrelas destacáveis para conjurar Míssil Mágico de 5º círculo e permite viajar para o Plano Astral como ação Usar Magia.",
    "descricao": "Concede +1 em todas as salvaguardas. Possui 6 estrelas destacáveis (1d6 recuperadas ao amanhecer) para conjurar *Míssil Mágico* de 5º círculo (7 dardos). Permite projetar-se juntamente com seus pertences para o Plano Astral com uma ação Usar Magia."
  },
  {
    "nome": "Túnica das Quinquilharias Úteis",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Túnica com retalhos removíveis que se transformam em objetos úteis reais instantaneamente (adagas, lanternas, espelhos, escadas, cães de montaria, bolsas de ouro, etc.).",
    "descricao": "Possui retalhos bordados destacáveis que se transformam no item real correspondente:\n- 2 Adagas\n- 2 Lanternas Furta-Fogo acesas\n- 2 Espelhos de Aço\n- 2 Varas de 3 metros\n- 2 Cordas de Cânhamo de 15 m\n- 2 Sacos de 100 PO\n- Retalhos adicionais: Bote de madeira, Mastim de montaria, Cavalo de montaria, Escada de 7,5 m, Poções de Cura Maior, Porta de Carvalho, etc."
  },
  {
    "nome": "Túnica do Arquimago",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização por um Bruxo, Feiticeiro ou Mago)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Bruxo, Feiticeiro ou Mago",
    "resumo": "Túnica suprema para conjuradores arcanos: CA base 15 + Destreza, Vantagem em todas as salvaguardas contra magias e +2 no CD de magias e bônus de ataque mágico.",
    "descricao": "Enquanto estiver vestindo esta elegante túnica:\n- Sua Classe de Armadura base se torna 15 + seu modificador de Destreza (se não estiver usando armadura).\n- Você tem Vantagem em todas as salvaguardas contra magias e outros efeitos mágicos.\n- A CD para evitar suas magias e suas jogadas de ataque mágico aumentam em +2."
  },
  {
    "nome": "Túnica Ocular",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Visão periférica de 360 graus, Vantagem em Percepção visual, Visão no Escuro de 36 metros e capacidade de enxergar criaturas invisíveis e no Plano Etéreo.",
    "descricao": "Adornada com dezenas de olhos mágicos bordados. Concede visão em todas as direções de 360 graus, Vantagem em testes de Percepção visual, Visão no Escuro de 36 metros e capacidade de enxergar criaturas Invisíveis e criaturas no Plano Etéreo a até 36 metros."
  },
  {
    "nome": "Unguento de Keoghtom",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pote com 1d4+1 doses; aplicar restaura 2d8+2 PV, neutraliza venenos e cura todas as doenças.",
    "descricao": "Pote de vidro contendo 1d4 + 1 doses de pomada espessa. Aplicar 1 dose em uma criatura restaura 2d8 + 2 Pontos de Vida, encerra a condição Envenenado e cura todas as doenças que a afetem."
  },
  {
    "nome": "Vara de Pesca",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Vara mágica com isca espectral que garante capturar 1 peixe fresco comestível a cada 10 minutos em qualquer corpo d'água.",
    "descricao": "Com uma linha espectral brilhante, pescar com esta vara em qualquer lago, rio ou mar garante a captura de 1 peixe fresco comestível de porte médio a cada 10 minutos de pesca relaxante."
  },
  {
    "nome": "Varinha Cuspidora de Fogo",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 7 cargas para conjurar Mãos Flamejantes (1 carga) ou Raio de Fogo (0 cargas) com CD 13.",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite conjurar *Mãos Flamejantes* de 1º círculo (1 carga) ou o truque *Raio de Fogo* (0 cargas) com CD 13."
  },
  {
    "nome": "Varinha das Maravilhas",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Raro (Requer Sintonização por um Conjurador)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para gerar efeitos caóticos selvagens e imprevisíveis rolando 1d100 (relâmpagos, bolas de fogo, tempestades de borboletas, petrificação, etc.).",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Ao gastar 1 carga apontando para um alvo, rola 1d100 para efeito mágico aleatório:\n- 01-05: Conjura Lentidão.\n- 06-10: Conjura Fogo das Fadas.\n- 11-15: Fica Atordoado até o próximo turno.\n- 16-20: Rajada de 600 borboletas brilhantes.\n- 21-25: Conjura Escuridão.\n- 26-30: Grama cresce em área de 18 m.\n- 31-35: 1d4 joias de 500 PO brotam.\n- 36-40: Fumaça densa.\n- 41-45: Conjura Aumentar/Reduzir.\n- 46-50: Conjura Bola de Fogo de 3º círculo.\n- 51-55: Pele fica azul-cobalto por 1d4 dias.\n- 56-60: Conjura Relâmpago de 3º círculo.\n- 61-65: Tempestade de chuva por 1 rodada.\n- 66-70: Alvo fica invisível.\n- 71-75: Folhas brotam no alvo.\n- 76-80: Conjura Levitação.\n- 81-85: 1d4 nuvens de vapor quente.\n- 86-90: Alvo começa a se transformar em pedra (Petrificado).\n- 91-95: Alvo é Polimorfado em um carneiro.\n- 96-100: Causa 10d6 de dano de força."
  },
  {
    "nome": "Varinha de Detectar Inimigo",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para detectar a direção e distância de qualquer criatura hostil a até 18 metros.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga como ação Usar Magia para sentir a direção e distância da criatura hostil mais próxima em um raio de 18 metros."
  },
  {
    "nome": "Varinha de Mísseis Mágicos",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 7 cargas para conjurar Míssil Mágico de 1º a 7º círculo (1 carga por círculo de magia).",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar de 1 a 7 cargas como ação Usar Magia para conjurar a magia *Míssil Mágico* (o círculo de conjuração é igual ao número de cargas gastas)."
  },
  {
    "nome": "Varinha de Orcus",
    "tipo": "Varinha",
    "subtipo": "Artefato",
    "tipo_linha": "Varinha, Artefato (Requer Sintonização por uma Criatura Sintonizada)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização e Lealdade a Orcus",
    "resumo": "Arma +3 senciente empunhável como maça (+2d12 dano necrótico); concede +3 na CA, invoca até 500 PV de mortos-vivos sob seu comando diário e conjura magias de 7 cargas (CD 18).",
    "descricao": "Cetro com crânio de obsidiana do Príncipe dos Mortos-Vivos. Funciona como Maça +3 causando +2d12 de dano Necrótico. Concede +3 na CA. Permite conjurar e erguer até 500 Pontos de Vida de Mortos-Vivos aliados leais diariamente. Possui 7 cargas para conjurar *Animar os Mortos*, *Bênção Nefasta*, *Círculo da Morte*, *Dedo da Morte*, *Falar com os Mortos* e *Palavra do Poder: Matar* (CD 18)."
  },
  {
    "nome": "Varinha de Paralisia",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Raro (Requer Sintonização por um Conjurador)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para disparar um raio paralisante em alvo a até 18 m (salvaguarda de Constituição CD 15 ou fica Paralisado por 1 minuto).",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga como ação Usar Magia para apontar para um alvo a até 18 metros: a criatura realiza salvaguarda de Constituição CD 15, ficando com a condição Paralisado por 1 minuto se falhar."
  },
  {
    "nome": "Varinha de Polimorfia",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Muito Raro (Requer Sintonização por um Conjurador)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para conjurar Polimorfia (CD 15) tendo como alvo uma criatura a até 18 metros.",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga como ação Usar Magia para conjurar a magia *Polimorfia* (CD 15 para evitar) em uma criatura à sua vista a até 18 metros."
  },
  {
    "nome": "Varinha de Relâmpagos",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Raro (Requer Sintonização por um Conjurador)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para conjurar Relâmpago (CD 15) de 3º a 9º círculo (1 carga base + 1 carga por círculo extra).",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga para conjurar *Relâmpago* de 3º círculo (CD 15 para evitar). Você pode gastar cargas adicionais para aumentar o círculo da magia em +1 por carga adicional gasta."
  },
  {
    "nome": "Varinha de Teia",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Incomum (Requer Sintonização por um Conjurador)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para conjurar Teia (CD 15) com alcance de 18 metros.",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga como ação Usar Magia para conjurar a magia *Teia* (CD 15 para evitar) com alcance de 18 metros."
  },
  {
    "nome": "Varinha do Mago de Guerra, +1, +2 ou +3",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Incomum (+1), Raro (+2) ou Muito Raro (+3) (Requer Sintonização por um Conjurador)",
    "raridade": "Incomum (+1), Raro (+2), Muito Raro (+3)",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Concede um bônus de +1, +2 ou +3 nas jogadas de ataque mágico e ignora Cobertura Parcial ao realizar ataques mágicos.",
    "descricao": "Enquanto estiver segurando esta varinha, você adquire um bônus em jogadas de ataque mágico determinado pela raridade da varinha (+1 Incomum, +2 Raro, +3 Muito Raro). Além disso, você ignora Cobertura Parcial e Três Quartos ao realizar jogadas de ataque mágico."
  },
  {
    "nome": "Varinha do Medo",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Raro (Requer Sintonização por um Conjurador)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para impor Comando: Fuja (1 carga, CD 15 Sab) ou emitir Cone de Terror de 18 m impondo Amedrontado (2 cargas, CD 15 Sab).",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga para forçar uma criatura a até 18 m a obedecer ao comando de fugir (CD 15 Sab), ou gastar 2 cargas para emitir um cone de 18 m de terror impondo a condição Amedrontado por 1 minuto (CD 15 Sab)."
  },
  {
    "nome": "Varinha dos Segredos",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 3 cargas para apontar na direção da porta secreta ou armadilha mais próxima a até 9 metros.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga como ação Usar Objeto para fazer a varinha pulsar e apontar na direção exata da porta secreta ou armadilha oculta mais próxima a até 9 metros de você."
  },
  {
    "nome": "Varinha Farejadora de Magias",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para conjurar Detectar Magia com alcance expandido a até 18 metros.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Permite gastar 1 carga como ação Usar Magia para conjurar a magia *Detectar Magia* com alcance estendido para 18 metros."
  },
  {
    "nome": "Varinha Imobilizadora",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Raro (Requer Sintonização por um Conjurador)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 7 cargas para conjurar Imobilizar Monstro (CD 15) em um alvo a até 18 metros.",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga como ação Usar Magia para conjurar a magia *Imobilizar Monstro* (CD 15 para evitar) com alcance de 18 metros."
  },
  {
    "nome": "Varinha Pirotécnica",
    "tipo": "Varinha",
    "subtipo": "",
    "tipo_linha": "Varinha, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 7 cargas para criar fogos de artifício coloridos e inofensivos explodindo no ar a até 18 metros.",
    "descricao": "Possui 7 cargas (1d6+1 ao amanhecer). Permite gastar 1 carga para lançar um feixe de luz que explode no ar como fogos de artifício inofensivos em cores vibrantes a até 18 metros."
  },
  {
    "nome": "Vassoura Dançante de Baba Yaga",
    "tipo": "Item Maravilhoso",
    "subtipo": "Artefato",
    "tipo_linha": "Item Maravilhoso, Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Vassoura animada senciente de combate e voo: Voo de 18 m, 2 ataques com cerdas espinhosas (+10 atq, 2d8+5 cortante) e varredura de poeira cegante.",
    "descricao": "Lendária vassoura mágica da bruxa Baba Yaga. Concede Deslocamento de Voo de 18 metros com capacidade para até 2 tripulantes. Em combate, atua como aliada senciente realizando 2 ataques corpo a corpo (+10 no ataque, 2d8+5 cortante) ou varrendo poeira em cone de 9 m impondo a condição Cego (CD 18 Con)."
  },
  {
    "nome": "Vassoura Voadora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Vassoura mágica de madeira que voa a até 15 m/turno (ou 9 m com até 180 kg) por palavra de comando.",
    "descricao": "Esta vassoura de madeira comum adquire um Deslocamento de Voo de 15 metros ao pronunciar sua palavra de comando. Pode suportar até 180 kg (reduzindo a velocidade para 9 metros se carregar mais de 90 kg). Permite que ela voe sozinha para um destino conhecido até 1,5 km."
  },
  {
    "nome": "Vela das Profundezas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Vela mágica impermeável que queima debaixo d'água emitindo luz por até 8 horas.",
    "descricao": "A chama desta vela não pode ser apagada por água e queima normalmente mesmo quando totalmente submersa, emitindo Luz Plena em 1,5 m e Meia-luz por mais 1,5 m por até 8 horas."
  },
  {
    "nome": "Vela de Invocação",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Queima por até 4 horas concedendo Vantagem em jogadas de ataque, testes e salvaguardas a criaturas de mesma tendência a até 9 m, ou pode ser queimada totalmente para conjurar Portal.",
    "descricao": "Sintonizada a uma tendência. Enquanto acesa (dura até 4 horas), criaturas da mesma tendência a até 9 m têm Vantagem em jogadas de ataque, testes de atributo e salvaguardas, e conjuradores podem conjurar magias de 1º círculo como truques. Alternativamente, queimar a vela inteira instantaneamente conjura a magia *Portal*."
  }
];
