module.exports = [
  {
    "nome": "Cachimbo Teratológico",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite exalar uma nuvem de fumaça em formato de criaturas (dragão, flunf, slaad, etc.).",
    "descricao": "Ao fumar este cachimbo, você pode executar uma ação Usar Magia para exalar uma nuvem de fumaça que assume a forma de uma criatura, como um dragão, um flunf ou um slaad (cubo de 30 cm)."
  },
  {
    "nome": "Cadeado Antiladinagem",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Pinos mágicos móveis impõem Desvantagem em testes de Destreza para arrombamento.",
    "descricao": "Este cadeado parece comum e vem com uma única chave. Os pinos se ajustam magicamente para frustrar ladrões. Testes de Destreza realizados para abrir o cadeado têm Desvantagem."
  },
  {
    "nome": "Cajado Avicular",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 10 cargas para produzir cantos e chilreios de diferentes tipos de aves até 36 metros.",
    "descricao": "Este cajado de madeira possui 10 cargas (1d6+4 ao amanhecer). Permite gastar 1 carga para emitir o som de aves (corvo, galinha, pato, águia, etc.) a até 36 m."
  },
  {
    "nome": "Cajado da Cura",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Raro (Requer Sintonização por um Bardo, Clérigo ou Druida)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Bardo, Clérigo ou Druida",
    "resumo": "Possui 10 cargas para conjurar Curar Ferimentos (1-4 cargas), Restauração Menor (2 cargas) e Curar Ferimentos em Massa (5 cargas).",
    "descricao": "Possui 10 cargas (1d6+4 ao amanhecer). Permite conjurar *Curar Ferimentos* (1 carga/círculo até 4º), *Restauração Menor* (2 cargas) e *Curar Ferimentos em Massa* (5 cargas)."
  },
  {
    "nome": "Cajado da Píton",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Pode ser arremessado no chão para transformar-se em uma Cobra Constritora Gigante sob seu controle.",
    "descricao": "Com uma ação Usar Magia, pode ser arremessado a até 3 m para virar uma **Cobra Constritora Gigante** sob seu controle mental. Reverte à forma de cajado com Ação Bônus curando todo PV. Destruído se atingir 0 PV."
  },
  {
    "nome": "Cajado da Trovoada Relampejante",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Cajado +2 com propriedades diárias de Golpe de Relâmpago (9d6 CD 17), Relâmpago (+2d6), Trovão (Atordoado) e Trovoada (2d6 trovejante em 18 m).",
    "descricao": "Cajado +2 em jogadas de ataque e dano.\n- **Golpe de Relâmpago:** Linha de 36 m causando 9d6 dano elétrico (CD 17 Des).\n- **Relâmpago:** Causa +2d6 dano elétrico em acerto corpo a corpo.\n- **Trovão:** Alvo atingido faz salvaguarda CD 17 Con ou fica Atordoado até o final do próximo turno.\n- **Trovão e Relâmpago:** Usa ambos no mesmo ataque com Ação Bônus.\n- **Trovoada:** Emanação de 18 m causando 2d6 dano trovejante e Surdez (CD 17 Con)."
  },
  {
    "nome": "Cajado da Víbora",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ação Bônus para transformar a ponta em Cobra Peçonhenta, atacando com bônus de Sabedoria e causando 1d6 perfurante + 3d6 veneno.",
    "descricao": "Como Ação Bônus, transforma a cabeça do cajado em Cobra Peçonhenta por 1 min. Em ataques, causa 1d6 perfurante + 3d6 venenoso usando Proficiência + Sabedoria."
  },
  {
    "nome": "Cajado das Matas",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Raro (Requer Sintonização por um Druida)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Druida",
    "resumo": "Cajado +2 (+2 ataques mágicos) com 6 cargas para magias de druida e capacidade de transformar-se em árvore de 18 m.",
    "descricao": "Cajado +2 em ataque/dano e +2 em jogadas de ataque mágico. Possui 6 cargas (1d6 ao amanhecer).\n- **Forma Arbórea:** Gasta 1 carga para virar árvore de 18 m de altura.\n- **Magias:** Amizade Animal (1), Despertar (5), Falar com Animais (1), Falar com Plantas (3), Localizar Animais/Plantas (2), Muralha de Espinhos (6), Passo Sem Rastro (2), Pele-casca (2)."
  },
  {
    "nome": "Cajado de Flores",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 10 cargas para fazer brotar flores aromáticas da terra ou do próprio cajado.",
    "descricao": "Possui 10 cargas (1d6+4 ao amanhecer). Permite gastar 1 carga para fazer brotar uma margarida ou outra flor da terra ou do cajado."
  },
  {
    "nome": "Cajado do Acrobata",
    "tipo": "Arma",
    "subtipo": "Cajado",
    "tipo_linha": "Arma (Cajado), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Cajado +2 mutável em cetro de 15 cm ou haste de 3 m; possui Arremesso retornante, Vantagem em Acrobacia e Reação de +5 CA contra um ataque.",
    "descricao": "Concede bônus de +2 em ataque e dano. Pode mudar de forma para cetro de 15 cm, haste de 3 m ou cajado.\n- **Arma à Distância:** Arremesso 9/36 m e retorna para a mão.\n- **Assistência Acrobática:** Vantagem em testes de Acrobacia.\n- **Deflexão de Ataque:** Reação concede +5 na CA contra um ataque (1x por descanso curto/longo)."
  },
  {
    "nome": "Cajado do Agravo",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Cajado +3 com 10 cargas; permite gastar até 3 cargas em acerto corpo a corpo para causar +1d6 dano Energético por carga.",
    "descricao": "Cajado +3 em jogadas de ataque e dano. Possui 10 cargas (1d6+4 ao amanhecer). Ao atingir com ataque corpo a corpo, gaste até 3 cargas para causar +1d6 pontos de dano Energético por carga."
  },
  {
    "nome": "Cajado do Definhamento",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas; ao acertar, pode causar +2d10 dano Necrótico e impor Desvantagem em testes/salvaguardas de Força e Con (CD 15).",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Ao acertar, pode gastar 1 carga para causar +2d10 pontos de dano Necrótico e forçar salvaguarda de Constituição CD 15 ou o alvo sofre Desvantagem por 1 hora em testes e salvaguardas de Força ou Constituição."
  },
  {
    "nome": "Cajado do Enxame de Insetos",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Raro (Requer Sintonização por um Bardo, Bruxo, Clérigo, Druida, Feiticeiro ou Mago)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Conjurador",
    "resumo": "Possui 10 cargas para conjurar Inseto Gigante (4), Praga de Insetos (5) ou criar Nuvem de Insetos obscurecente de 9 m (1 carga).",
    "descricao": "Possui 10 cargas (1d6+4 ao amanhecer). Permite conjurar *Inseto Gigante* (4 cargas), *Praga de Insetos* (5 cargas) ou criar uma Nuvem de Insetos em emanação de 9 metros por 10 minutos (1 carga)."
  },
  {
    "nome": "Cajado do Fogo",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Muito Raro (Requer Sintonização por um Bruxo, Druida, Feiticeiro ou Mago)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Bruxo, Druida, Feiticeiro ou Mago",
    "resumo": "Resistência a dano Ígneo e 10 cargas para conjurar Mãos Flamejantes (1), Bola de Fogo (3) e Muralha de Fogo (4).",
    "descricao": "Concede Resistência a dano Ígneo. Possui 10 cargas (1d6+4 ao amanhecer) para conjurar *Mãos Flamejantes* (1), *Bola de Fogo* (3) e *Muralha de Fogo* (4)."
  },
  {
    "nome": "Cajado do Gelo",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Muito Raro (Requer Sintonização por um Bruxo, Druida, Feiticeiro ou Mago)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Bruxo, Druida, Feiticeiro ou Mago",
    "resumo": "Resistência a dano Gélido e 10 cargas para conjurar Névoa Obscurecente (1), Muralha de Gelo (4), Tempestade Glacial (4) e Cone de Frio (5).",
    "descricao": "Concede Resistência a dano Gélido. Possui 10 cargas (1d6+4 ao amanhecer) para conjurar *Névoa Obscurecente* (1), *Muralha de Gelo* (4), *Tempestade Glacial* (4) e *Cone de Frio* (5)."
  },
  {
    "nome": "Cajado do Poder",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Muito Raro (Requer Sintonização por um Bruxo, Feiticeiro ou Mago)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Bruxo, Feiticeiro ou Mago",
    "resumo": "Cajado +2 (+2 CA, salvaguardas e ataque mágico), 20 cargas para magias poderosas e Golpe Retributivo explosivo.",
    "descricao": "Cajado +2 em ataque/dano, +2 na CA, salvaguardas e ataque mágico. Possui 20 cargas (2d8+4 ao amanhecer).\n- **Magias (CD 17):** Mísseis Mágicos (1), Raio do Enfraquecimento (1), Levitação (2), Bola de Fogo 5º (5), Cone de Frio (5), Muralha de Energia (5), Paralisar Monstro (5), Relâmpago 5º (5), Globo de Invulnerabilidade (6).\n- **Golpe Retributivo:** Quebra o cajado liberando explosão devastadora de dano energético."
  },
  {
    "nome": "Cajado dos Magi",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Lendário (Requer Sintonização por um Bruxo, Feiticeiro ou Mago)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Bruxo, Feiticeiro ou Mago",
    "resumo": "Cajado +2 com 50 cargas, absorção de magias, Vantagem em salvaguardas contra magias, repertório imenso de magias e Golpe Retributivo.",
    "descricao": "Cajado +2 em ataque e +2 em ataque mágico. Vantagem em salvaguardas contra magias. Reação para absorver magias direcionadas a você, convertendo em cargas. Possui 50 cargas (4d6+2 ao amanhecer).\n- **Magias sem custo:** Detectar Magia, Aumentar/Reduzir, Luz, Mãos Mágicas, Proteção contra o Bem e Mal, Tranca Arcana.\n- **Magias com custo:** Teia (2), Arrombar (2), Invisibilidade (2), Esfera Flamejante (2), Dissipar Magia (3), Muralha de Fogo (4), Tempestade Glacial (4), Criar Passagem (5), Telecinese (5), Bola de Fogo 7º (7), Relâmpago 7º (7), Invocar Elemental (7), Transição Planar (7)."
  },
  {
    "nome": "Cajado dos Sortilégios",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Raro (Requer Sintonização por um Bardo, Bruxo, Clérigo, Druida, Feiticeiro ou Mago)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Conjurador",
    "resumo": "Possui 10 cargas para Comando, Compreender Idiomas ou Enfeitiçar Pessoa; permite refletir e resistir a encantamentos.",
    "descricao": "Possui 10 cargas (1d8+2 ao amanhecer). Permite conjurar *Comando*, *Compreender Idiomas* ou *Enfeitiçar Pessoa* (1 carga). Pode refletir magias de Encantamento com Reação (1 carga) ou transformar falha de salvaguarda em sucesso 1x ao dia."
  },
  {
    "nome": "Cajado Magificado",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Raridade Varia (Requer Sintonização por um Conjurador)",
    "raridade": "Raridade Variável",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Conjurador",
    "resumo": "Contém uma magia vinculada de 8º círculo ou inferior de qualquer escola (6 cargas, 1d6 diário).",
    "descricao": "Contém uma magia vinculada de até 8º círculo. Possui 6 cargas (1d6 ao amanhecer) para conjurar a magia vinculada."
  },
  {
    "nome": "Cajado Ornamental",
    "tipo": "Cajado",
    "subtipo": "",
    "tipo_linha": "Cajado, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite fazer até 3 objetos minúsculos flutuarem e girarem a 2,5 cm do topo do cajado.",
    "descricao": "Permite posicionar até 3 objetos Minúsculos de até 0,5 kg para flutuarem a 2,5 cm da ponta do cajado, girando ou movendo-se lentamente."
  },
  {
    "nome": "Caldeirão do Renascimento",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização por um Bruxo ou Druida)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Bruxo ou Druida",
    "resumo": "Foco de conjuração e componente para Vidência; permite preparar Poção de Cura Maior diária e reviver humanoides com sal (1x a cada 7 dias).",
    "descricao": "Serve como foco de conjuração e componente para *Vidência*.\n- **Preparar Poção:** Cria 1 *Poção de Cura (maior)* após cada Descanso Longo (dura 24h).\n- **Reviver os Mortos:** Cresce para tamanho Médio; ao cobrir um cadáver de Humanoide com 90 kg de sal por 8 horas, traz a criatura de volta à vida como em *Reviver os Mortos* (1x a cada 7 dias)."
  },
  {
    "nome": "Caneca da Sobriedade",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite beber qualquer bebida alcoólica colocada nela sem sofrer embriaguez.",
    "descricao": "Esta caneca possui um rosto sério esculpido em um dos lados. Você pode beber cerveja, vinho ou qualquer outra bebida alcoólica não mágica colocada nela sem ficar embriagado."
  },
  {
    "nome": "Capa Aracnídea",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Imunidade a teias, Deslocamento de Escalada com mãos livres, Resistência a Veneno e conjura Teia ampliada 1x ao dia.",
    "descricao": "Concede imunidade a aprisionamento em teias, Deslocamento de Escalada com mãos livres no teto/paredes, Resistência a dano Venenoso e conjura *Teia* com dobro da área 1x ao dia."
  },
  {
    "nome": "Capa de Muitas Modas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ação Bônus para alterar estilo, cor e qualidade aparente da capa à vontade.",
    "descricao": "Enquanto estiver vestindo esta capa, você pode executar uma Ação Bônus para alterar o estilo, a cor e a qualidade aparente dela."
  },
  {
    "nome": "Capa Deslocadora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Projeta ilusão de deslocamento que impõe Desvantagem em ataques contra você (suprimida temporariamente ao sofrer dano).",
    "descricao": "Projeta magicamente uma ilusão que impõe Desvantagem em todas as jogadas de ataque contra você. Se você sofrer dano, a propriedade deixa de funcionar até o início do seu próximo turno."
  },
  {
    "nome": "Capa do Povo Élfico",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Vantagem em testes de Furtividade e Desvantagem em testes de Percepção para notá-lo.",
    "descricao": "Enquanto estiver usando esta capa, testes de Sabedoria (Percepção) realizados para notá-lo têm Desvantagem e você tem Vantagem em testes de Destreza (Furtividade)."
  },
  {
    "nome": "Capa do Saltimbanco",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite conjurar Porta Dimensional como ação Usar Magia 1x ao dia, deixando fumaça para trás.",
    "descricao": "Permite conjurar *Porta Dimensional* como ação Usar Magia 1x ao dia. Ao se teleportar, deixa uma nuvem de fumaça que obscurece parcialmente o espaço de origem."
  },
  {
    "nome": "Capa Esvoaçante",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ação Bônus para fazê-la ondular dramaticamente por 1 minuto.",
    "descricao": "Enquanto estiver vestindo esta capa, você pode executar uma Ação Bônus para fazê-la ondular dramaticamente por 1 minuto."
  },
  {
    "nome": "Carrilhão Destrancador",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Tubo metálico de 10 usos para conjurar Arrombar com tom retumbante audível a 90 metros.",
    "descricao": "Como ação Usar Magia, toca o carrilhão para conjurar *Arrombar* (som audível a 90 m). Pode ser usado 10 vezes antes de quebrar."
  },
  {
    "nome": "Cetro da Absorção",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Reação para absorver magias que tenham você como alvo (armazena até 50 círculos) e convertê-las em espaços de magia até 5º círculo.",
    "descricao": "Reação para absorver uma magia que tem você como único alvo sem área de efeito, cancelando-a e acumulando seus círculos. Pode converter os círculos acumulados em espaços de magia de até 5º círculo."
  },
  {
    "nome": "Cetro da Prontidão",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Vantagem em Percepção e Iniciativa; conjura magias de detecção e cria Aura Protetora de +1 CA/salvaguardas.",
    "descricao": "Concede Vantagem em Percepção e Iniciativa. Conjura *Detectar Magia*, *Detectar o Bem e o Mal*, *Detectar Veneno e Doença* e *Ver o Invisível*. Pode ser fincado no chão para criar Aura Protetora de 18 m (+1 CA, +1 salvaguardas e revela invisíveis) por 10 min 1x/dia."
  },
  {
    "nome": "Cetro da Regência",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Apresenta o cetro para impor a condição Enfeitiçado por 8 horas em criaturas à sua escolha a até 36 m (CD 15 Sab).",
    "descricao": "Com uma ação Usar Magia, força criaturas a até 36 metros a realizarem salvaguarda de Sabedoria CD 15 ou ficam Enfeitiçadas por 8 horas considerando você um líder confiável (1x ao dia)."
  },
  {
    "nome": "Cetro da Segurança",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Transporta você e até 199 criaturas para um semiplano paradisíaco e seguro com sustento e descanso acelerado (1x a cada 10 dias).",
    "descricao": "Transporta você e até 199 criaturas voluntárias para um semiplano seguro de formato personalizável, com comida, água, cura acelerada e suspensão de envelhecimento (1x a cada 10 dias)."
  },
  {
    "nome": "Cetro de Poder Magistral",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Maça +3 com 6 botões funcionais (espada flamejante, machado +3, lança +3, escada de 15 m, aríete +10, bússola) e poderes de drenar vida, paralisar e aterrorizar.",
    "descricao": "Funciona como Maça +3. Possui 6 botões: 1. Espada flamejante (+2d6 fogo); 2. Machado de Batalha +3; 3. Lança +3; 4. Escada de 15 m; 5. Aríete (+10 Atletismo); 6. Bússola e profundímetro.\nAlém disso, possui propriedades de Drenar Vida (4d6 necrótico CD 17 Con), Paralisar (CD 17 Con) e Aterrorizar em 9 m (CD 17 Sab)."
  },
  {
    "nome": "Cetro de Ressurreição",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 5 cargas para conjurar Cura Completa (1 carga) ou Ressurreição (5 cargas), recuperando 1 carga diária.",
    "descricao": "Possui 5 cargas (1 recuperada ao amanhecer). Permite conjurar *Cura Completa* (1 carga) ou *Ressurreição* (5 cargas)."
  },
  {
    "nome": "Cetro do Protetor do Pacto",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Incomum (+1), Raro (+2) ou Muito Raro (+3) (Requer Sintonização por um Bruxo)",
    "raridade": "Incomum (+1), Raro (+2), Muito Raro (+3)",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Bruxo",
    "resumo": "Concede bônus de +1 a +3 no ataque e CD de magias de Bruxo, e permite recuperar 1 espaço de magia de Bruxo por Descanso Longo.",
    "descricao": "Concede bônus de +1, +2 ou +3 em ataques mágicos e CDs de salvaguarda de Bruxo. Permite recuperar 1 espaço de magia de Bruxo como ação Usar Magia 1x por Descanso Longo."
  },
  {
    "nome": "Cetro Imóvel",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Fixa-se magicamente no espaço ao pressionar o botão, suportando até 4 toneladas.",
    "descricao": "Ao pressionar o botão com ação Usar Objeto, o cetro fixa-se magicamente no ar desafiando a gravidade e suportando até 4 toneladas (Força Atletismo CD 30 para movê-lo)."
  },
  {
    "nome": "Cetro Tentacular",
    "tipo": "Cetro",
    "subtipo": "",
    "tipo_linha": "Cetro, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ação para realizar 3 ataques de tentáculos (+9 atq, 1d6 psíquico); se todos acertarem, impõe Contido e 3d6 dano psíquico por turno.",
    "descricao": "Com uma ação Usar Magia, realiza 3 ataques de tentáculos a até 4,5 m (+9 no ataque, 1d6 psíquico). Se os três acertarem o mesmo alvo, ele deve ser bem-sucedido em salvaguarda de Destreza CD 15 ou fica Contido sofrendo 3d6 pontos de dano Psíquico por turno."
  },
  {
    "nome": "Chapéu das Muitas Magias",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização por um Mago)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Mago",
    "resumo": "Foco de Mago; permite tentar puxar e conjurar magias desconhecidas gastando espaço e teste de Arcanismo (ou gera efeitos selvagens hilários).",
    "descricao": "Serve como foco de conjuração (componente somático de puxar do chapéu). Permite tentar conjurar magia desconhecida de Mago com teste de Arcanismo CD 10 + círculo. Se falhar, rola 1d100 para efeito aleatório (borboletas, chuva de animais, objetos, petrificação temporária ou portais)."
  },
  {
    "nome": "Chapéu do Embuço",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite conjurar a magia Disfarçar-se à vontade enquanto usado.",
    "descricao": "Enquanto estiver vestindo este Chapéu, você pode conjurar a magia *Disfarçar-se*. A magia se encerra se o chapéu for removido."
  },
  {
    "nome": "Chapéu dos Magos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização por um Mago)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por um Mago",
    "resumo": "Foco de conjuração de Mago que permite tentar conjurar um truque desconhecido com teste de Arcanismo CD 10.",
    "descricao": "Serve como Foco de Conjuração para Mago e permite tentar conjurar um truque que não conhece da lista de Mago realizando teste de Arcanismo CD 10 (1x por Descanso Longo)."
  },
  {
    "nome": "Chapéu dos Vermes",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 3 cargas para invocar um Morcego, Rato ou Sapo inofensivo do interior do chapéu.",
    "descricao": "Possui 3 cargas (recuperadas ao amanhecer). Permite gastar 1 carga para invocar um Morcego, Rato ou Sapo inofensivo que tenta se afastar de você."
  },
  {
    "nome": "Chave Misteriosa",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 5% de chance de destrancar qualquer fechadura na qual seja inserida, desaparecendo após o sucesso.",
    "descricao": "A chave possui 5% de chance de destrancar qualquer fechadura na qual esteja inserida. Assim que destranca algo, a chave desaparece."
  },
  {
    "nome": "Chifre de Escutar",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Suprime os efeitos da condição Surdo enquanto segurado contra a orelha.",
    "descricao": "Enquanto segurar este chifre contra sua orelha, ele suprime os efeitos da condição Surdo em você."
  },
  {
    "nome": "Chifre do Alarme Silencioso",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 4 cargas para soprar um som audível exclusivamente para uma única criatura escolhida a até 180 metros.",
    "descricao": "Possui 4 cargas (1d4 ao amanhecer). Permite soprar o chifre para que uma criatura escolhida a até 180 m escute o estrondo. Nenhuma outra criatura ouve nada."
  },
  {
    "nome": "Cimitarra da Velocidade",
    "tipo": "Arma",
    "subtipo": "Cimitarra",
    "tipo_linha": "Arma (Cimitarra), Muito Rara (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Cimitarra +2 que permite realizar um ataque extra com ela como Ação Bônus em cada turno.",
    "descricao": "Você adquire um bônus de +2 em jogadas de ataque e dano realizadas com esta arma mágica. Além disso, você pode realizar um ataque com ela como uma Ação Bônus em cada um dos seus turnos."
  },
  {
    "nome": "Cinturão de Força de Gigante",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raridade Variável (Requer Sintonização)",
    "raridade": "Raridade Variável",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Fixa o valor de Força em 21 (Colina), 23 (Pedra/Gelo), 25 (Fogo), 27 (Nuvens) ou 29 (Tempestade).",
    "descricao": "Ao usar este cinturão, seu valor de Força muda para o fornecido pelo item conforme o tipo de gigante:\n- Colina: Força 21 (Raro)\n- Pedra/Gelo: Força 23 (Muito Raro)\n- Fogo: Força 25 (Muito Raro)\n- Nuvens: Força 27 (Lendário)\n- Tempestade: Força 29 (Lendário)"
  },
  {
    "nome": "Cinturão do Povo Anão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "+2 Constituição (máx 20), Vantagem em Persuasão com anões, idioma Anão, e para não-anões: Resistência a Veneno e Visão no Escuro 18 m.",
    "descricao": "Concede +2 Constituição (máx 20), idioma Anão e Vantagem em Persuasão com anões. Se não for anão, confere Resistência a dano Venenoso, Vantagem contra Envenenado e Visão no Escuro de 18 metros. 50% de chance diária de crescer uma barba espessa."
  },
  {
    "nome": "Cola Suprema",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Adesivo mágico permanente que une dois objetos inseparavelmente em 1 minuto (removível apenas com Solvente Universal ou Desejo).",
    "descricao": "Forma uma ligação adesiva permanente entre dois objetos após 1 minuto de cura. Desfeita apenas com *Solvente Universal*, *Óleo de Forma Etérea* ou *Desejo*."
  },
  {
    "nome": "Colar da Adaptabilidade",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite respirar normalmente em qualquer ambiente e concede Vantagem em salvaguardas contra Envenenado.",
    "descricao": "Ao usar este colar, você pode respirar normalmente em qualquer ambiente e tem Vantagem em salvaguardas realizadas para evitar ou encerrar a condição Envenenado."
  },
  {
    "nome": "Colar de Bolas de Fogo",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Contém 1d6+3 contas detonáveis como Bola de Fogo de 3º círculo (CD 15), podendo arremessar várias juntas para somar dano.",
    "descricao": "Possui 1d6+3 contas destacáveis. Com ação Usar Magia, arremessa uma conta até 18 m para detonar como *Bola de Fogo* de 3º círculo (8d6 de fogo, CD 15). Arremessar contas adicionais aumenta o dano em +1d6 por conta extra."
  },
  {
    "nome": "Colar de Contas de Oração",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização por um Clérigo, Druida ou Paladino)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização por Clérigo, Druida ou Paladino",
    "resumo": "Contém 1d4+2 contas mágicas que permitem conjurar magias divinas como Ação Bônus 1x ao dia cada.",
    "descricao": "Contém contas mágicas que podem conjurar como Ação Bônus (1x ao dia cada): Bênção, Curar Ferimentos 2º círculo, Restauração Maior, Destruição Radiante, Defensor da Fé ou Caminhar no Vento."
  },
  {
    "nome": "Colar dos Pensamentos",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 5 cargas para conjurar Detectar Pensamentos (CD 13) a partir dele.",
    "descricao": "O colar tem 5 cargas (1d4 ao amanhecer). Permite gastar 1 carga para conjurar *Detectar Pensamentos* (CD 13 para evitar)."
  },
  {
    "nome": "Conta de Hidratação",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Dissolve-se em líquido transformando até meio litro em água potável fresca e gelada.",
    "descricao": "Ao ser colocada em um líquido, esta esfera esponjosa, gelatinosa e insípida dissolve-se, transformando até meio litro de um líquido em água potável fresca e gelada."
  },
  {
    "nome": "Conta de Nutrição",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Dissolve na língua fornecendo nutrição equivalente a um dia inteiro de rações.",
    "descricao": "Esta esfera esponjosa, gelatinosa e insípida dissolve na língua e fornece nutrição equivalente a um dia de Rações."
  },
  {
    "nome": "Contas Energéticas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Esferas arremessáveis que causam 5d4 dano Energético (CD 15 Des) e prendem criaturas em esfera impenetrável por 1 minuto.",
    "descricao": "Arremessada a até 18 m, explode em esfera de 3 m de raio causando 5d4 dano Energético (CD 15 Des). Alvos que falharem ficam aprisionados em uma esfera impenetrável transparente por 1 minuto."
  },
  {
    "nome": "Corda Autorreparadora",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Corda de 15 metros que se une e reconecta magicamente com ação Usar Magia ao ser cortada.",
    "descricao": "Esta corda enrolada de 15 metros é capaz de se reparar quando cortada em qualquer número de pedaços menores através de uma ação Usar Magia."
  },
  {
    "nome": "Corda de Emaranhamento",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Corda de 9 m que dispara para conter uma criatura a até 6 m (CD 15 Des / Atletismo para escapar).",
    "descricao": "Com ação Usar Magia, comanda a corda a disparar e enredar alvo a até 6 m (salvaguarda de Destreza CD 15 ou fica Contido). Possui CA 20 e 20 PV."
  },
  {
    "nome": "Corda Encantada",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Corda animada de 18 metros que se move, amarra, desata e cria nós concedendo Vantagem em escalada.",
    "descricao": "Suporta até 1.500 kg. Move-se até 3 m/turno por comando verbal para prender-se, atar-se ou criar nós largos a cada 30 cm que conferem Vantagem em testes de escalada."
  },
  {
    "nome": "Corselete de Couro Deslumbrante",
    "tipo": "Armadura",
    "subtipo": "Armadura de Couro Batido",
    "tipo_linha": "Armadura (Armadura de Couro Batido), Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Armadura +1 na CA com capacidade ilusória de assumir a aparência de qualquer roupa ou armadura como Ação Bônus.",
    "descricao": "Enquanto estiver vestindo esta armadura, você recebe um bônus de +1 na Classe de Armadura e pode executar uma Ação Bônus para fazê-la assumir a aparência de qualquer vestimenta ou armadura."
  },
  {
    "nome": "Cota de Malha Élfica",
    "tipo": "Armadura",
    "subtipo": "Cota de Malha ou Parcial",
    "tipo_linha": "Armadura (Cota de Malha ou Cota de Malha Parcial), Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede +1 na CA e o usuário é considerado proficiente com ela mesmo sem treinamento em armaduras médias/pesadas.",
    "descricao": "Enquanto estiver usando esta armadura você adquire um bônus de +1 na Classe de Armadura. Você é considerado proficiente com esta armadura, mesmo se não tiver treinamento com armaduras Médias ou Pesadas."
  },
  {
    "nome": "Cota de Malha Ifriti",
    "tipo": "Armadura",
    "subtipo": "Cota de Malha ou Parcial",
    "tipo_linha": "Armadura (Cota de Malha ou Cota de Malha Parcial), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede +3 na CA, Imunidade a dano Ígneo, idioma Primordial e permite caminhar sobre lava/magma como solo firme.",
    "descricao": "Concede +3 na Classe de Armadura, Imunidade a dano Ígneo e idioma Primordial. Permite caminhar sobre rocha derretida e lava como se fosse chão firme."
  },
  {
    "nome": "Cubo de Invocação",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro",
    "raridade": "Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Caixa de música que conjura magia de invocação de 5º círculo (Aberração, Fera, Constructo, Dragão, Elemental ou Feérico) 1x/dia sem Concentração.",
    "descricao": "Ao torcer a manivela como ação Usar Magia, conjura uma magia de invocação de 5º círculo sem necessidade de Concentração (1d6: 1. Invocar Aberração; 2. Invocar Fera; 3. Invocar Constructo; 4. Invocar Dragão; 5. Convocar Elemental; 6. Convocar Feérico). 1x ao dia."
  },
  {
    "nome": "Cubo Energético",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 10 cargas para conjurar Armadura Arcana (1), Escudo Arcano (1), Pequeno Refúgio (3), Esfera Resiliente (4), Santuário Particular (4) e Muralha de Energia (5).",
    "descricao": "Possui 10 cargas (1d6 ao amanhecer). Permite conjurar *Armadura Arcana* (1), *Escudo Arcano* (1), *Pequeno Refúgio de Leomund* (3), *Esfera Resiliente de Otiluke* (4), *Santuário Particular de Mordenkainen* (4) e *Muralha de Energia* (5) com CD 17."
  },
  {
    "nome": "Cubo-Portal",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Possui 3 cargas para abrir Portal planar ou conjurar Transição Planar para 6 planos de existência conectados às faces do cubo.",
    "descricao": "Possui 3 cargas (1d3 ao amanhecer). Pressionar uma face conjura *Portal* para o plano conectado; pressionar duas vezes conjura *Transição Planar*."
  },
  {
    "nome": "Dado do Charlatão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum (Requer Sintonização)",
    "raridade": "Comum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Permite controlar voluntariamente o número obtido em qualquer rolagem deste dado de 6 lados.",
    "descricao": "Sempre que você jogar este dado de seis lados, você pode controlar qual número obtido na jogada."
  },
  {
    "nome": "Defensora",
    "tipo": "Arma",
    "subtipo": "Qualquer Arma Corpo a Corpo",
    "tipo_linha": "Arma (Qualquer Arma Corpo a Corpo), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Arma +3 que permite transferir parte ou todo o seu bônus de ataque/dano para a Classe de Armadura em cada turno.",
    "descricao": "Você recebe um bônus de +3 em jogadas de ataque e dano realizadas com esta arma mágica. No primeiro ataque de cada turno, pode transferir parte ou todo o bônus para a sua Classe de Armadura até o início do seu próximo turno."
  },
  {
    "nome": "Demonômico de Iggwilv",
    "tipo": "Item Maravilhoso",
    "subtipo": "Artefato",
    "tipo_linha": "Item Maravilhoso, Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Tomo sombrio supremo de demonologia: Vantagem em testes sobre o Abismo, aprisionamento de Ínferos em páginas, dano maximizado contra Ínferos e magias de 8 cargas.",
    "descricao": "Tratado lendário de demonologia de Iggwilv.\n- **Conhecimento Abissal:** Vantagem em Arcanismo/Sobrevivência sobre demônios e Abismo.\n- **Contenção:** Aprisiona Ínferos em páginas em branco (CD 20 Car).\n- **Enredamento:** Conjura Âncora Planar e Círculo Mágico como 9º círculo com Desvantagem para o Ínfero.\n- **Flagelo Ínfero:** Dano maximizado contra Ínferos.\n- **Magias (8 cargas, CD 20):** Gargalhada Nefasta de Tasha (0), Círculo Mágico (1), Âncora Planar (2), Aliado Extraplanar (3), Invocar Ínfero (3), Receptáculo Arcano (3), Transição Planar para o Abismo (3)."
  },
  {
    "nome": "Diadema da Explosão",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite conjurar Raio Ardente com bônus de ataque de +5 uma vez ao dia.",
    "descricao": "Enquanto estiver vestindo esta diadema, você pode conjurar *Raio Ardente* com ela (bônus de +5 para acertar) 1x ao dia."
  },
  {
    "nome": "Dispositivo de Kwalish",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Veículo subaquático e terrestre blindado (CA 20, 200 PV) em formato de lagosta mecânica operado por 10 alavancas.",
    "descricao": "Barril mecânico blindado de 250 kg para 2 tripulantes com ar para 10h e submersão até 275 m. Possui 10 alavancas para locomoção, visão, iluminação, garras de ataque (+8, 2d6 ou contenção) e flutuação."
  },
  {
    "nome": "Elmo da Compreensão de Idiomas",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Permite conjurar Compreender Idiomas à vontade enquanto usado.",
    "descricao": "Enquanto estiver vestindo este elmo, você pode conjurar *Compreender Idiomas* a partir dele."
  },
  {
    "nome": "Elmo de Telepatia",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede telepatia de 9 metros e permite conjurar Detectar Pensamentos e Sugestão (CD 13) 1x ao dia.",
    "descricao": "Enquanto estiver usando este elmo, você tem telepatia com alcance de 9 metros, e pode conjurar *Detectar Pensamentos* ou *Sugestão* (CD 13 para evitar) 1x ao dia."
  },
  {
    "nome": "Elmo de Teleporte",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Possui 3 cargas para conjurar a magia Teleporte a partir dele.",
    "descricao": "Este elmo tem 3 cargas (1d3 recuperadas ao amanhecer). Permite gastar 1 carga para conjurar *Teleporte* a partir dele."
  },
  {
    "nome": "Elmo do Esplendor",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Cravejado de joias mágicas: armas em chamas (+1d6 fogo), aura contra mortos-vivos (1d6 radiante), Resistência a Fogo e magias consumindo gemas.",
    "descricao": "Cravejado com diamantes, rubis e opalas.\n- **Chamas:** Arma em chamas causando +1d6 dano Ígneo.\n- **Luz Diamantina:** Mortos-vivos em 9 m sofrem 1d6 radiante por turno.\n- **Resistência de Rubi:** Resistência a dano Ígneo.\n- **Magias:** Luz do Dia (opala), Bola de Fogo (opala de fogo), Rajada Prismática (diamante), Muralha de Fogo (rubi)."
  },
  {
    "nome": "Elmo do Medo",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Faz os olhos brilharem em vermelho e o rosto ficar envolto em sombras sinistras.",
    "descricao": "Enquanto estiver usando este temível elmo de aço, seus olhos brilham em vermelho e o resto do rosto fica escondido na sombra."
  },
  {
    "nome": "Escara Gélida",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive, Rapieira), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Causa +1d6 dano Gélido em acertos, confere Resistência a dano Ígneo, ilumina no frio e extingue chamas a até 9 m ao sacar.",
    "descricao": "Causa 1d6 pontos de dano Gélido adicionais em acertos. Concede Resistência a dano Ígneo. Emite luz no frio e permite extinguir chamas não mágicas a até 9 metros ao sacar."
  },
  {
    "nome": "Escaravelho de Proteção",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede +1 CA, Vantagem em salvaguardas contra magias e 12 cargas para converter falhas contra Necromancia/mortos-vivos em sucessos.",
    "descricao": "Concede bônus de +1 na CA e Vantagem em salvaguardas contra magias. Possui 12 cargas: ao falhar em salvaguarda contra Necromancia ou mortos-vivos, gasta 1 carga como Reação para transformar a falha em sucesso."
  },
  {
    "nome": "Escudo Animado",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ação Bônus para fazê-lo flutuar e protegê-lo no seu espaço por 1 minuto mantendo as duas mãos livres.",
    "descricao": "Com uma Ação Bônus, o escudo salta e paira protegendo você como se estivesse empunhado, deixando ambas as mãos livres por 1 minuto."
  },
  {
    "nome": "Escudo Apanhador de Flechas",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "+2 na CA contra ataques à distância (+4 total) e Reação para interceptar ataques à distância mirando aliados a até 1,5 m.",
    "descricao": "Bônus de +2 adicional na CA contra ataques à distância. Reação para tornar-se o alvo de ataques à distância disparados contra criaturas a até 1,5 m de você."
  },
  {
    "nome": "Escudo Bloqueador de Magias",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Concede Vantagem em salvaguardas contra magias e efeitos mágicos, e impõe Desvantagem em ataques mágicos contra você.",
    "descricao": "Ao estar equipado com este Escudo, você tem Vantagem em salvaguardas contra magias e outros efeitos mágicos, e jogadas de ataque mágico têm Desvantagem contra você."
  },
  {
    "nome": "Escudo de Atração de Projéteis",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Resistência a dano de armas à distância; amaldiçoado atraindo ataques disparados contra aliados a até 3 m.",
    "descricao": "Concede Resistência a dano de armas à distância.\n\n***Maldição.*** Sempre que um ataque com arma à distância tiver como alvo criatura a até 3 m de você, a maldição redireciona o ataque para você."
  },
  {
    "nome": "Escudo do Cavaleiro",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Escudo +2 na CA com Campo de Proteção invulnerável de 1,5 m (1 min) e Pancada Forte (2d6+2 dano energético + empurrão de 3 m e Caído).",
    "descricao": "Bônus de +2 adicional na CA.\n- **Campo de Proteção:** Reação cria emanação de 1,5 m imune a danos e efeitos por 1 min (1x/dia).\n- **Pancada Forte:** Ataque corpo a corpo causando 2d6+2 + Força em dano Energético, empurrando o alvo 3 m e derrubando-o Caído."
  },
  {
    "nome": "Escudo Expressivo",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Ação Bônus para alterar a expressão do rosto estampado no escudo.",
    "descricao": "O Escudo está estampado com o símbolo de um rosto. Ao ter este Escudo equipado, você pode executar uma Ação Bônus para alterar a expressão do rosto."
  },
  {
    "nome": "Escudo Sentinela",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Incomum",
    "raridade": "Incomum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede Vantagem em jogadas de Iniciativa e testes de Sabedoria (Percepção).",
    "descricao": "Ao ter este Escudo equipado, você tem Vantagem em jogadas de Iniciativa e testes de Sabedoria (Percepção). O Escudo está estampado com o símbolo de um olho."
  },
  {
    "nome": "Escudo, +1, +2 ou +3",
    "tipo": "Armadura",
    "subtipo": "Escudo",
    "tipo_linha": "Armadura (Escudo), Incomum (+1), Raro (+2) ou Muito Raro (+3)",
    "raridade": "Incomum (+1), Raro (+2), Muito Raro (+3)",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Concede um bônus adicional de +1, +2 ou +3 na Classe de Armadura além dos +2 normais do escudo.",
    "descricao": "Ao ter este Escudo equipado, você tem um bônus na Classe de Armadura determinado pela raridade do Escudo (+1 Incomum, +2 Raro, +3 Muito Raro), além do bônus normal do Escudo para a CA."
  },
  {
    "nome": "Esfera da Aniquilação",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Lendário",
    "raridade": "Lendário",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Esfera negra de 60 cm que desintegra toda matéria ao contato causando 8d10 dano Energético (controlável por teste Arcanismo CD 25).",
    "descricao": "Ruptura planar que aniquila matéria causando 8d10 pontos de dano Energético. Pode ser controlada mentalmente a até 18 m com teste de Arcanismo CD 25."
  },
  {
    "nome": "Esfera da Direção",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Foco arcano que aponta a direção do norte magnético com ação Usar Magia.",
    "descricao": "Pode ser usada como Foco Arcano. Permite descobrir o norte magnético com uma ação Usar Magia."
  },
  {
    "nome": "Esfera do Tempo",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Foco arcano que informa se é manhã, tarde, noite ou madrugada no Plano Material.",
    "descricao": "Pode ser usada como Foco Arcano. Permite descobrir o período do dia (manhã, tarde, noite ou madrugada) com ação Usar Magia."
  },
  {
    "nome": "Espada da Precisão",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Grande, Longa ou Glaive",
    "tipo_linha": "Arma (Cimitarra, Espada Grande, Espada Longa ou Glaive), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Dano maximizado contra objetos; no resultado 20 em criaturas, causa +14 dano Cortante e 1 nível de Exaustão.",
    "descricao": "Maximiza os dados de dano contra objetos. Ao obter 20 natural no d20 contra criatura, causa 14 pontos de dano Cortante adicionais e impõe 1 nível de Exaustão ao alvo."
  },
  {
    "nome": "Espada da Vingança",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive ou Rapieira), Incomum (Requer Sintonização)",
    "raridade": "Incomum",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Espada +1 amaldiçoada com espírito vingativo: força a atacar o causador de dano em caso de falha em Sabedoria CD 15.",
    "descricao": "Espada +1. Possui maldição: impõe Desvantagem com outras armas e, ao sofrer dano em combate, deve passar em salvaguarda de Sabedoria CD 15 ou é forçado a atacar o agressor até derrotá-lo."
  },
  {
    "nome": "Espada Dançarina",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Rapieira), Muito Raro (Requer Sintonização)",
    "raridade": "Muito Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Ação Bônus para lançá-la no ar pairando e atacando até 9 metros por 4 vezes antes de retornar à sua mão.",
    "descricao": "Com uma Ação Bônus, voa até 9 metros e ataca alvos a até 1,5 m dela usando suas estatísticas. Pode atacar até 4 vezes antes de retornar voando para sua mão."
  },
  {
    "nome": "Espada das Respostas",
    "tipo": "Arma",
    "subtipo": "Espada Longa",
    "tipo_linha": "Arma (Espada Longa), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Espada Longa +3 que permite Reação de contra-ataque corpo a corpo com Vantagem e ignorando resistências/imunidades.",
    "descricao": "Bônus de +3 em ataque e dano. Permite usar uma Reação para atacar com Vantagem qualquer criatura adjacente que cause dano a você, ignorando qualquer Resistência ou Imunidade do alvo."
  },
  {
    "nome": "Espada de Kas",
    "tipo": "Arma",
    "subtipo": "Espada Longa",
    "tipo_linha": "Arma (Espada Longa), Artefato (Requer Sintonização)",
    "raridade": "Artefato",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Artefato senciente +3 (+2d10 cortante contra mortos-vivos, crítico 19-20), +1d10 na Iniciativa, defesa adaptável, Resistência a Necrótico e magias lendárias.",
    "descricao": "Lendária espada forjada para destruir Vecna. Bônus de +3 em ataque/dano, crítico 19-20 e +2d10 cortante contra mortos-vivos. Concede +1d10 na Iniciativa, permite transferir bônus de ataque para a CA e concede Resistência a dano Necrótico. Conjura *Convocar Relâmpagos*, *Dedo da Morte* e *Palavra Sagrada* (CD 18). Arma senciente sedenta por sangue."
  },
  {
    "nome": "Espada Laceradora",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive ou Rapieira), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Causa +2d6 dano Necrótico e impede o alvo de recuperar Pontos de Vida por 1 hora (CD 15 Con).",
    "descricao": "Ao atingir uma criatura, causa 2d6 pontos de dano Necrótico adicionais e o alvo deve passar em salvaguarda de Constituição CD 15 ou não poderá recuperar PV por 1 hora."
  },
  {
    "nome": "Espada Lunar",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive, Rapieira), Comum",
    "raridade": "Comum",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Emite luz prateada de luar em 4,5 m de raio plena e 4,5 m meia-luz quando desembainhada na escuridão.",
    "descricao": "Na Escuridão, a lâmina desembainhada desta arma emite a luz do luar, criando Luz Plena em um raio de 4,5 metros e Meia-luz por mais 4,5 metros."
  },
  {
    "nome": "Espada Usurpadora de Vida",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Curta, Grande, Longa, Glaive ou Rapieira",
    "tipo_linha": "Arma (Cimitarra, Espada Curta, Espada Grande, Espada Longa, Glaive ou Rapieira), Raro (Requer Sintonização)",
    "raridade": "Raro",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "No resultado 20 natural, causa +15 dano Necrótico a criaturas vivas e concede 15 PV temporários ao portador.",
    "descricao": "Ao obter 20 no d20 na jogada de ataque contra alvo que não seja Constructo ou Morto-Vivo, causa 15 pontos de dano Necrótico adicionais e concede Pontos de Vida Temporários iguais ao dano necrótico causado."
  },
  {
    "nome": "Espada Vorpal",
    "tipo": "Arma",
    "subtipo": "Cimitarra, Espada Grande, Longa ou Glaive",
    "tipo_linha": "Arma (Cimitarra, Espada Grande, Espada Longa ou Glaive), Lendário (Requer Sintonização)",
    "raridade": "Lendário",
    "sintonizacao": true,
    "detalhe_sintonizacao": "Requer Sintonização",
    "resumo": "Espada +3 que ignora Resistência a Cortante e decapita criaturas instantaneamente no resultado 20 natural (ou causa +30 dano cortante).",
    "descricao": "Concede +3 em ataque e dano e ignora Resistência a dano Cortante. Ao rolar 20 natural contra criatura com cabeça, decepa-lhe a cabeça matando-a instantaneamente (ou causa 30 pontos de dano Cortante adicionais se for imune a decapitação)."
  },
  {
    "nome": "Espelho Aprisionador de Vida",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Muito Raro",
    "raridade": "Muito Raro",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Espelho ativado que aprisiona criaturas que olharem seu reflexo a até 9 m em doze celas extradimensionais (CD 15 Car).",
    "descricao": "Espelho ativado por palavra de comando. Criaturas a até 9 m que vejam seu reflexo devem passar em salvaguarda de Carisma CD 15 ou ficam presas em uma das 12 celas extradimensionais. Permite comunicar-se ou libertar prisioneiros com comandos verbais."
  },
  {
    "nome": "Estatueta de Poder Maravilhoso",
    "tipo": "Item Maravilhoso",
    "subtipo": "",
    "tipo_linha": "Item Maravilhoso, Raridade Variável",
    "raridade": "Raridade Variável",
    "sintonizacao": false,
    "detalhe_sintonizacao": "",
    "resumo": "Estatuetas de bolso que se transformam em criaturas vivas aliadas e montarias (Cabras de Marfim, Cão de Ônix, Corcel de Obsidiana, Mosca de Ébano, Leões de Ouro, etc.).",
    "descricao": "Com uma ação Usar Magia ao arremessar no chão a até 18 m, transforma-se em uma criatura aliada:\n- **Cabras de Marfim (Raro):** Labuta, Viagem e Terror.\n- **Cão de Ônix (Raro):** Mastim falante com Visão às Cegas 18 m por até 6h.\n- **Corcel de Obsidiana (Muito Raro):** Pesadelo por até 24h.\n- **Coruja de Serpentina (Raro):** Coruja Gigante telepática por até 8h.\n- **Corvo de Prata (Incomum):** Corvo por até 12h (permite Mensageiro Animal).\n- **Elefante de Mármore (Raro):** Elefante por até 24h.\n- **Grifo de Bronze (Raro):** Grifo por até 6h.\n- **Leões de Ouro (Raro):** Dois leões por até 1h.\n- **Mosca de Ébano (Raro):** Mosca Gigante voadora montável por até 12h."
  }
];
